### ISSUE TITLE
Cannot generate @nrwl/angular:lib

### ISSUE THREAD

**Issue by zpydee** [nrwl/nx#13544]
## Current Behavior

I have gone through an upgrade of nx from v13 to @latest over a couple of days, and I am no longer able to generate angular libs which has kind of ground me to a halt

## Expected Behavior

generate @nrwl/angular:lib should work (Ihave tried on console and through nx console, with the same failure result

## Steps to Reproduce

i wish i could, but i obviously did something wrong during the upgrade process,

### Failure Logs / Images / Videos

I believe the wanrings in the beginning part of the log are appratently unimportant, but as you'll see the script does error.

the error message is surprising since the lib mentioned is the one i'm trying to generate.

```bash
*[d3js][~/dev/collabli]$ nx g @nrwl/angular:lib feat-sandbox --directory shared --tags scope:shared,stack:client,type:feat,version:0 --simpleModuleName

>  NX  Generating @nrwl/angular:library

[NX] Angular devkit readJsonWorkspace fell back to Nx workspaces logic
Project 'features-pinboards-feat-highlighted-pins' contains extension with invalid name (files).
Project 'features-pinboards-feat-pinboard-drawers' contains extension with invalid name (files).
Project 'features-pinboards-feat-pinboard-tools' contains extension with invalid name (files).
Project 'features-pinboards-feat-resize-handles' contains extension with invalid name (files).
Project 'features-pinboards-store-pinboards' contains extension with invalid name (files).
Project 'features-pinboards-util-pinboards' contains extension with invalid name (files).
Project 'conversations-feat-conversations' contains extension with invalid name (files).
Project 'features-feat-task-board-drawers' contains extension with invalid name (files).
Project 'features-pinboards-feat-pinboard' contains extension with invalid name (files).
Project 'apps-collabli-util-environment' contains extension with invalid name (files).
Project 'features-feat-workspace-tools' contains extension with invalid name (files).
Project 'apps-collabli-feat-dashboard' contains extension with invalid name (files).
Project 'apps-collabli-util-providers' contains extension with invalid name (files).
Project 'models-feat-account-instance' contains extension with invalid name (files).
Project 'apps-collabli-feat-canvases' contains extension with invalid name (files).
Project 'apps-collabli-feat-outcomes' contains extension with invalid name (files).
Project 'features-pinboards-feat-pin' contains extension with invalid name (files).
Project 'apps-collabli-feat-kanbans' contains extension with invalid name (files).
Project 'integrations-util-usersnap' contains extension with invalid name (files).
Project 'models-feat-model-instance' contains extension with invalid name (files).
Project 'models-feat-task-checklist' contains extension with invalid name (files).
Project 'features-store-task-board' contains extension with invalid name (files).
Project 'models-feat-user-instance' contains extension with invalid name (files).
Project 'shared-feat-billing-plans' contains extension with invalid name (files).
Project 'features-feat-task-board' contains extension with invalid name (files).
Project 'features-store-workspace' contains extension with invalid name (files).
Project 'models-feat-join-account' contains extension with invalid name (files).
Project 'models-feat-linked-model' contains extension with invalid name (files).
Project 'models-feat-model-avatar' contains extension with invalid name (files).
Project 'session-store-membership' contains extension with invalid name (files).
Project 'features-feat-workspace' contains extension with invalid name (files).
Project 'features-store-features' contains extension with invalid name (files).
Project 'models-feat-add-account' contains extension with invalid name (files).
Project 'models-feat-model-lists' contains extension with invalid name (files).
Project 'apps-collabli-feat-app' contains extension with invalid name (files).
Project 'models-store-instances' contains extension with invalid name (files).
Project 'features-store-mailer' contains extension with invalid name (files).
Project 'models-feat-add-model' contains extension with invalid name (files).
Project 'models-feat-solutions' contains extension with invalid name (files).
Project 'models-ui-model-cards' contains extension with invalid name (files).
Project 'models-ui-model-table' contains extension with invalid name (files).
Project 'session-feat-settings' contains extension with invalid name (files).
Project 'session-store-session' contains extension with invalid name (files).
Project 'shared-feat-shortcuts' contains extension with invalid name (files).
Project 'storage-feat-uploader' contains extension with invalid name (files).
Project 'features-feat-mailer' contains extension with invalid name (files).
Project 'models-feat-accounts' contains extension with invalid name (files).
Project 'models-feat-canvases' contains extension with invalid name (files).
Project 'session-feat-session' contains extension with invalid name (files).
Project 'session-ui-reloading' contains extension with invalid name (files).
Project 'shared-ui-doodle-pad' contains extension with invalid name (files).
Project 'shared-ui-scrollable' contains extension with invalid name (files).
Project 'shared-util-language' contains extension with invalid name (files).
Project 'shell-store-sidebars' contains extension with invalid name (files).
Project 'storage-util-storage' contains extension with invalid name (files).
Project 'collabli-pwa-v0-e2e' contains extension with invalid name (files).
Project 'db-util-db-entities' contains extension with invalid name (files).
Project 'features-feat-share' contains extension with invalid name (files).
Project 'features-feat-start' contains extension with invalid name (files).
Project 'shared-feat-buttons' contains extension with invalid name (files).
Project 'shared-feat-dialogs' contains extension with invalid name (files).
Project 'shared-ui-rich-text' contains extension with invalid name (files).
Project 'shared-ui-shortcuts' contains extension with invalid name (files).
Project 'shared-util-objects' contains extension with invalid name (files).
Project 'shell-feat-sidebars' contains extension with invalid name (files).
Project 'shell-store-hotkeys' contains extension with invalid name (files).
Project 'collabli-server-v0' contains extension with invalid name (files).
Project 'features-feat-help' contains extension with invalid name (files).
Project 'features-feat-task' contains extension with invalid name (files).
Project 'models-feat-squads' contains extension with invalid name (files).
Project 'models-store-lists' contains extension with invalid name (files).
Project 'shared-feat-system' contains extension with invalid name (files).
Project 'shared-feat-wizard' contains extension with invalid name (files).
Project 'shared-ui-calendar' contains extension with invalid name (files).
Project 'shared-ui-dropzone' contains extension with invalid name (files).
Project 'shared-util-arrays' contains extension with invalid name (files).
Project 'shared-util-client' contains extension with invalid name (files).
Project 'shared-util-colors' contains extension with invalid name (files).
Project 'shell-store-snacks' contains extension with invalid name (files).
Project 'collabli-site-e2e' contains extension with invalid name (files).
Project 'db-store-entities' contains extension with invalid name (files).
Project 'features-feat-pin' contains extension with invalid name (files).
Project 'models-feat-ideas' contains extension with invalid name (files).
Project 'models-feat-tasks' contains extension with invalid name (files).
Project 'models-feat-users' contains extension with invalid name (files).
Project 'shared-ui-panzoom' contains extension with invalid name (files).
Project 'shared-ui-ribbons' contains extension with invalid name (files).
Project 'shared-util-dates' contains extension with invalid name (files).
Project 'shared-util-money' contains extension with invalid name (files).
Project 'shell-store-shell' contains extension with invalid name (files).
Project 'models-feat-tags' contains extension with invalid name (files).
Project 'shared-ui-canvas' contains extension with invalid name (files).
Project 'shared-ui-search' contains extension with invalid name (files).
Project 'shell-feat-shell' contains extension with invalid name (files).
Project 'shell-store-tips' contains extension with invalid name (files).
Project 'store-data-store' contains extension with invalid name (files).
Project 'store-store-core' contains extension with invalid name (files).
Project 'auth-store-auth' contains extension with invalid name (files).
Project 'collabli-pwa-v0' contains extension with invalid name (files).
Project 'shared-glossary' contains extension with invalid name (files).
Project 'shared-ui-chips' contains extension with invalid name (files).
Project 'shared-ui-click' contains extension with invalid name (files).
Project 'shared-ui-media' contains extension with invalid name (files).
Project 'shared-ui-oauth' contains extension with invalid name (files).
Project 'shell-ui-snacks' contains extension with invalid name (files).
Project 'auth-feat-auth' contains extension with invalid name (files).
Project 'auth-util-auth' contains extension with invalid name (files).
Project 'shared-ui-info' contains extension with invalid name (files).
Project 'shared-ui-tips' contains extension with invalid name (files).
Project 'shared-util-d3' contains extension with invalid name (files).
Project 'collabli-site' contains extension with invalid name (files).
Project 'shared-ui-nav' contains extension with invalid name (files).
Project 'db-util-db' contains extension with invalid name (files).
[NX] Angular devkit readJsonWorkspace fell back to Nx workspaces logic
Project 'features-pinboards-feat-highlighted-pins' contains extension with invalid name (files).
Project 'features-pinboards-feat-pinboard-drawers' contains extension with invalid name (files).
Project 'features-pinboards-feat-pinboard-tools' contains extension with invalid name (files).
Project 'features-pinboards-feat-resize-handles' contains extension with invalid name (files).
Project 'features-pinboards-store-pinboards' contains extension with invalid name (files).
Project 'features-pinboards-util-pinboards' contains extension with invalid name (files).
Project 'conversations-feat-conversations' contains extension with invalid name (files).
Project 'features-feat-task-board-drawers' contains extension with invalid name (files).
Project 'features-pinboards-feat-pinboard' contains extension with invalid name (files).
Project 'apps-collabli-util-environment' contains extension with invalid name (files).
Project 'features-feat-workspace-tools' contains extension with invalid name (files).
Project 'apps-collabli-feat-dashboard' contains extension with invalid name (files).
Project 'apps-collabli-util-providers' contains extension with invalid name (files).
Project 'models-feat-account-instance' contains extension with invalid name (files).
Project 'apps-collabli-feat-canvases' contains extension with invalid name (files).
Project 'apps-collabli-feat-outcomes' contains extension with invalid name (files).
Project 'features-pinboards-feat-pin' contains extension with invalid name (files).
Project 'apps-collabli-feat-kanbans' contains extension with invalid name (files).
Project 'integrations-util-usersnap' contains extension with invalid name (files).
Project 'models-feat-model-instance' contains extension with invalid name (files).
Project 'models-feat-task-checklist' contains extension with invalid name (files).
Project 'features-store-task-board' contains extension with invalid name (files).
Project 'models-feat-user-instance' contains extension with invalid name (files).
Project 'shared-feat-billing-plans' contains extension with invalid name (files).
Project 'features-feat-task-board' contains extension with invalid name (files).
Project 'features-store-workspace' contains extension with invalid name (files).
Project 'models-feat-join-account' contains extension with invalid name (files).
Project 'models-feat-linked-model' contains extension with invalid name (files).
Project 'models-feat-model-avatar' contains extension with invalid name (files).
Project 'session-store-membership' contains extension with invalid name (files).
Project 'features-feat-workspace' contains extension with invalid name (files).
Project 'features-store-features' contains extension with invalid name (files).
Project 'models-feat-add-account' contains extension with invalid name (files).
Project 'models-feat-model-lists' contains extension with invalid name (files).
Project 'apps-collabli-feat-app' contains extension with invalid name (files).
Project 'models-store-instances' contains extension with invalid name (files).
Project 'features-store-mailer' contains extension with invalid name (files).
Project 'models-feat-add-model' contains extension with invalid name (files).
Project 'models-feat-solutions' contains extension with invalid name (files).
Project 'models-ui-model-cards' contains extension with invalid name (files).
Project 'models-ui-model-table' contains extension with invalid name (files).
Project 'session-feat-settings' contains extension with invalid name (files).
Project 'session-store-session' contains extension with invalid name (files).
Project 'shared-feat-shortcuts' contains extension with invalid name (files).
Project 'storage-feat-uploader' contains extension with invalid name (files).
Project 'features-feat-mailer' contains extension with invalid name (files).
Project 'models-feat-accounts' contains extension with invalid name (files).
Project 'models-feat-canvases' contains extension with invalid name (files).
Project 'session-feat-session' contains extension with invalid name (files).
Project 'session-ui-reloading' contains extension with invalid name (files).
Project 'shared-ui-doodle-pad' contains extension with invalid name (files).
Project 'shared-ui-scrollable' contains extension with invalid name (files).
Project 'shared-util-language' contains extension with invalid name (files).
Project 'shell-store-sidebars' contains extension with invalid name (files).
Project 'storage-util-storage' contains extension with invalid name (files).
Project 'collabli-pwa-v0-e2e' contains extension with invalid name (files).
Project 'db-util-db-entities' contains extension with invalid name (files).
Project 'features-feat-share' contains extension with invalid name (files).
Project 'features-feat-start' contains extension with invalid name (files).
Project 'shared-feat-buttons' contains extension with invalid name (files).
Project 'shared-feat-dialogs' contains extension with invalid name (files).
Project 'shared-ui-rich-text' contains extension with invalid name (files).
Project 'shared-ui-shortcuts' contains extension with invalid name (files).
Project 'shared-util-objects' contains extension with invalid name (files).
Project 'shell-feat-sidebars' contains extension with invalid name (files).
Project 'shell-store-hotkeys' contains extension with invalid name (files).
Project 'collabli-server-v0' contains extension with invalid name (files).
Project 'features-feat-help' contains extension with invalid name (files).
Project 'features-feat-task' contains extension with invalid name (files).
Project 'models-feat-squads' contains extension with invalid name (files).
Project 'models-store-lists' contains extension with invalid name (files).
Project 'shared-feat-system' contains extension with invalid name (files).
Project 'shared-feat-wizard' contains extension with invalid name (files).
Project 'shared-ui-calendar' contains extension with invalid name (files).
Project 'shared-ui-dropzone' contains extension with invalid name (files).
Project 'shared-util-arrays' contains extension with invalid name (files).
Project 'shared-util-client' contains extension with invalid name (files).
Project 'shared-util-colors' contains extension with invalid name (files).
Project 'shell-store-snacks' contains extension with invalid name (files).
Project 'collabli-site-e2e' contains extension with invalid name (files).
Project 'db-store-entities' contains extension with invalid name (files).
Project 'features-feat-pin' contains extension with invalid name (files).
Project 'models-feat-ideas' contains extension with invalid name (files).
Project 'models-feat-tasks' contains extension with invalid name (files).
Project 'models-feat-users' contains extension with invalid name (files).
Project 'shared-ui-panzoom' contains extension with invalid name (files).
Project 'shared-ui-ribbons' contains extension with invalid name (files).
Project 'shared-util-dates' contains extension with invalid name (files).
Project 'shared-util-money' contains extension with invalid name (files).
Project 'shell-store-shell' contains extension with invalid name (files).
Project 'models-feat-tags' contains extension with invalid name (files).
Project 'shared-ui-canvas' contains extension with invalid name (files).
Project 'shared-ui-search' contains extension with invalid name (files).
Project 'shell-feat-shell' contains extension with invalid name (files).
Project 'shell-store-tips' contains extension with invalid name (files).
Project 'store-data-store' contains extension with invalid name (files).
Project 'store-store-core' contains extension with invalid name (files).
Project 'auth-store-auth' contains extension with invalid name (files).
Project 'collabli-pwa-v0' contains extension with invalid name (files).
Project 'shared-glossary' contains extension with invalid name (files).
Project 'shared-ui-chips' contains extension with invalid name (files).
Project 'shared-ui-click' contains extension with invalid name (files).
Project 'shared-ui-media' contains extension with invalid name (files).
Project 'shared-ui-oauth' contains extension with invalid name (files).
Project 'shell-ui-snacks' contains extension with invalid name (files).
Project 'auth-feat-auth' contains extension with invalid name (files).
Project 'auth-util-auth' contains extension with invalid name (files).
Project 'shared-ui-info' contains extension with invalid name (files).
Project 'shared-ui-tips' contains extension with invalid name (files).
Project 'shared-util-d3' contains extension with invalid name (files).
Project 'collabli-site' contains extension with invalid name (files).
Project 'shared-ui-nav' contains extension with invalid name (files).
Project 'db-util-db' contains extension with invalid name (files).
[NX] Angular devkit called `writeWorkspace`, this may have had unintended consequences in angular.json
[NX] Double check angular.json before proceeding
[NX] Angular devkit readJsonWorkspace fell back to Nx workspaces logic
Project 'features-pinboards-feat-highlighted-pins' contains extension with invalid name (files).
Project 'features-pinboards-feat-pinboard-drawers' contains extension with invalid name (files).
Project 'features-pinboards-feat-pinboard-tools' contains extension with invalid name (files).
Project 'features-pinboards-feat-resize-handles' contains extension with invalid name (files).
Project 'features-pinboards-store-pinboards' contains extension with invalid name (files).
Project 'features-pinboards-util-pinboards' contains extension with invalid name (files).
Project 'conversations-feat-conversations' contains extension with invalid name (files).
Project 'features-feat-task-board-drawers' contains extension with invalid name (files).
Project 'features-pinboards-feat-pinboard' contains extension with invalid name (files).
Project 'apps-collabli-util-environment' contains extension with invalid name (files).
Project 'features-feat-workspace-tools' contains extension with invalid name (files).
Project 'apps-collabli-feat-dashboard' contains extension with invalid name (files).
Project 'apps-collabli-util-providers' contains extension with invalid name (files).
Project 'models-feat-account-instance' contains extension with invalid name (files).
Project 'apps-collabli-feat-canvases' contains extension with invalid name (files).
Project 'apps-collabli-feat-outcomes' contains extension with invalid name (files).
Project 'features-pinboards-feat-pin' contains extension with invalid name (files).
Project 'apps-collabli-feat-kanbans' contains extension with invalid name (files).
Project 'integrations-util-usersnap' contains extension with invalid name (files).
Project 'models-feat-model-instance' contains extension with invalid name (files).
Project 'models-feat-task-checklist' contains extension with invalid name (files).
Project 'features-store-task-board' contains extension with invalid name (files).
Project 'models-feat-user-instance' contains extension with invalid name (files).
Project 'shared-feat-billing-plans' contains extension with invalid name (files).
Project 'features-feat-task-board' contains extension with invalid name (files).
Project 'features-store-workspace' contains extension with invalid name (files).
Project 'models-feat-join-account' contains extension with invalid name (files).
Project 'models-feat-linked-model' contains extension with invalid name (files).
Project 'models-feat-model-avatar' contains extension with invalid name (files).
Project 'session-store-membership' contains extension with invalid name (files).
Project 'features-feat-workspace' contains extension with invalid name (files).
Project 'features-store-features' contains extension with invalid name (files).
Project 'models-feat-add-account' contains extension with invalid name (files).
Project 'models-feat-model-lists' contains extension with invalid name (files).
Project 'apps-collabli-feat-app' contains extension with invalid name (files).
Project 'models-store-instances' contains extension with invalid name (files).
Project 'features-store-mailer' contains extension with invalid name (files).
Project 'models-feat-add-model' contains extension with invalid name (files).
Project 'models-feat-solutions' contains extension with invalid name (files).
Project 'models-ui-model-cards' contains extension with invalid name (files).
Project 'models-ui-model-table' contains extension with invalid name (files).
Project 'session-feat-settings' contains extension with invalid name (files).
Project 'session-store-session' contains extension with invalid name (files).
Project 'shared-feat-shortcuts' contains extension with invalid name (files).
Project 'storage-feat-uploader' contains extension with invalid name (files).
Project 'features-feat-mailer' contains extension with invalid name (files).
Project 'models-feat-accounts' contains extension with invalid name (files).
Project 'models-feat-canvases' contains extension with invalid name (files).
Project 'session-feat-session' contains extension with invalid name (files).
Project 'session-ui-reloading' contains extension with invalid name (files).
Project 'shared-ui-doodle-pad' contains extension with invalid name (files).
Project 'shared-ui-scrollable' contains extension with invalid name (files).
Project 'shared-util-language' contains extension with invalid name (files).
Project 'shell-store-sidebars' contains extension with invalid name (files).
Project 'storage-util-storage' contains extension with invalid name (files).
Project 'collabli-pwa-v0-e2e' contains extension with invalid name (files).
Project 'db-util-db-entities' contains extension with invalid name (files).
Project 'features-feat-share' contains extension with invalid name (files).
Project 'features-feat-start' contains extension with invalid name (files).
Project 'shared-feat-buttons' contains extension with invalid name (files).
Project 'shared-feat-dialogs' contains extension with invalid name (files).
Project 'shared-ui-rich-text' contains extension with invalid name (files).
Project 'shared-ui-shortcuts' contains extension with invalid name (files).
Project 'shared-util-objects' contains extension with invalid name (files).
Project 'shell-feat-sidebars' contains extension with invalid name (files).
Project 'shell-store-hotkeys' contains extension with invalid name (files).
Project 'collabli-server-v0' contains extension with invalid name (files).
Project 'features-feat-help' contains extension with invalid name (files).
Project 'features-feat-task' contains extension with invalid name (files).
Project 'models-feat-squads' contains extension with invalid name (files).
Project 'models-store-lists' contains extension with invalid name (files).
Project 'shared-feat-system' contains extension with invalid name (files).
Project 'shared-feat-wizard' contains extension with invalid name (files).
Project 'shared-ui-calendar' contains extension with invalid name (files).
Project 'shared-ui-dropzone' contains extension with invalid name (files).
Project 'shared-util-arrays' contains extension with invalid name (files).
Project 'shared-util-client' contains extension with invalid name (files).
Project 'shared-util-colors' contains extension with invalid name (files).
Project 'shell-store-snacks' contains extension with invalid name (files).
Project 'collabli-site-e2e' contains extension with invalid name (files).
Project 'db-store-entities' contains extension with invalid name (files).
Project 'features-feat-pin' contains extension with invalid name (files).
Project 'models-feat-ideas' contains extension with invalid name (files).
Project 'models-feat-tasks' contains extension with invalid name (files).
Project 'models-feat-users' contains extension with invalid name (files).
Project 'shared-ui-panzoom' contains extension with invalid name (files).
Project 'shared-ui-ribbons' contains extension with invalid name (files).
Project 'shared-util-dates' contains extension with invalid name (files).
Project 'shared-util-money' contains extension with invalid name (files).
Project 'shell-store-shell' contains extension with invalid name (files).
Project 'models-feat-tags' contains extension with invalid name (files).
Project 'shared-ui-canvas' contains extension with invalid name (files).
Project 'shared-ui-search' contains extension with invalid name (files).
Project 'shell-feat-shell' contains extension with invalid name (files).
Project 'shell-store-tips' contains extension with invalid name (files).
Project 'store-data-store' contains extension with invalid name (files).
Project 'store-store-core' contains extension with invalid name (files).
Project 'auth-store-auth' contains extension with invalid name (files).
Project 'collabli-pwa-v0' contains extension with invalid name (files).
Project 'shared-glossary' contains extension with invalid name (files).
Project 'shared-ui-chips' contains extension with invalid name (files).
Project 'shared-ui-click' contains extension with invalid name (files).
Project 'shared-ui-media' contains extension with invalid name (files).
Project 'shared-ui-oauth' contains extension with invalid name (files).
Project 'shell-ui-snacks' contains extension with invalid name (files).
Project 'auth-feat-auth' contains extension with invalid name (files).
Project 'auth-util-auth' contains extension with invalid name (files).
Project 'shared-ui-info' contains extension with invalid name (files).
Project 'shared-ui-tips' contains extension with invalid name (files).
Project 'shared-util-d3' contains extension with invalid name (files).
Project 'collabli-site' contains extension with invalid name (files).
Project 'shared-ui-nav' contains extension with invalid name (files).
Project 'db-util-db' contains extension with invalid name (files).
SchematicsException [Error]: Project "shared-feat-sandbox" does not exist.
    at /Users/benji/dev/collabli/node_modules/@schematics/angular/component/index.js:32:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

 >  NX   Project "shared-feat-sandbox" does not exist.

   Pass --verbose to see the stacktrace.

*[d3js][~/dev/collabli]$ 
Ï
```

### Environment

```bash
*[d3js][~/dev/collabli]$ nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.14.2
   OS   : darwin arm64
   npm  : 8.5.0
   
   nx : 15.2.4
   @nrwl/angular : 15.2.4
   @nrwl/cypress : 15.2.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.2.4
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.2.4
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.2.4
   @nrwl/js : 15.2.4
   @nrwl/linter : 15.2.4
   @nrwl/nest : 15.2.4
   @nrwl/next : Not Found
   @nrwl/node : 15.2.4
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.2.4
   @nrwl/web : Not Found
   @nrwl/webpack : 15.2.4
   @nrwl/workspace : 15.2.4
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @ngrx/component-store: 14.0.2
   	 @ngrx/effects: 14.0.2
   	 @ngrx/entity: 14.0.2
   	 @ngrx/router-store: 14.0.2
   	 @ngrx/store: 14.0.2
   	 @ngrx/schematics: 14.0.2
   	 @ngrx/store-devtools: 14.0.2
   	 eslint-plugin-ngrx: 2.1.4

*[d3js][~/dev/collabli]$ 

```

**Comment by zpydee** [comment]
> 

👍

**Comment by Coly010** [comment]
Hey :) is there any way you could provide a repo that reproduces this? I'll need to see the state of your workspace to understand why this could be happening.

**Comment by SandeepThomas** [comment]
@Coly010 

I got the same issue on a newly generated repo for testing the micro frontend on the latest version.

1. npx create-nx-workspace@latest - use blank
2. npm install -D @nrwl/angular
3. nx g @nrwl/angular:host shell
4. nx g @nrwl/angular:lib shared

Getting error: cannot find tsconfig.json

note: there is no tsconfig.json on the root folder on the auto-generated repo

**Comment by Coly010** [comment]
@SandeepThomas I cannot reproduce this error.

Can you post the result of `nx report`? 

Also, when prompted to choose what workspace to create, you'll be given the following options:

```
 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

? Choose what to create                 …
Package-based monorepo: Nx makes it fast, but lets you run things your way.
Integrated monorepo:    Nx configures your favorite frameworks and lets you focus on shipping features.
Standalone React app:   Nx configures Vite and ESLint.
Standalone Angular app: Nx configures Jest, ESLint and Cypress.
```

What option did you select?

**Comment by SandeepThomas** [comment]
Option 1. I will give you a detailed error message within sometime.

**Comment by kenatwex** [comment]
same here im getting wrecked

`
w509297@w-702782 Yeti-UI %  node node_modules/@nrwl/cli/bin/nx.js generate @nrwl/angular:library --name=graphql --directory=shared/root/security  --prefix=yeti --tags=type:util --unitTestRunner=jest --importPath=@yeti/shared-root-security-graphql --strict --linter=eslint --standaloneConfig --compilationMode=partial --viewEncapsulation=Emulated --changeDetection=Default --style=scss --no-interactive --dry-run 


>  NX  Generating @nrwl/angular:library

[NX] Angular devkit readJsonWorkspace fell back to Nx workspaces logic
Workspace extension with invalid name (pluginsConfig) found.
Project 'shared-root-security-ui-authenticate' contains extension with invalid name (files).
Project 'shared-root-ui-notification' contains extension with invalid name (files).
Project 'shared-root-security-auth' contains extension with invalid name (files).
Project 'shared-root-ui-components' contains extension with invalid name (files).
Project 'shared-root-environment' contains extension with invalid name (files).
Project 'shared-root-animations' contains extension with invalid name (files).
Project 'shared-root-isomorphic' contains extension with invalid name (files).
Project 'shared-root-ui-feature' contains extension with invalid name (files).
Project 'shared-root-constants' contains extension with invalid name (files).
Project 'shared-root-ui-assets' contains extension with invalid name (files).
Project 'shared-root-ui-common' contains extension with invalid name (files).
Project 'shared-root-ui-styles' contains extension with invalid name (files).
Project 'shared-root-logging' contains extension with invalid name (files).
Project 'shared-root-config' contains extension with invalid name (files).
Project 'shared-root-models' contains extension with invalid name (files).
Project 'shared-root-core' contains extension with invalid name (files).
Project 'ui-dashboard-e2e' contains extension with invalid name (files).
Project 'ui-navigation' contains extension with invalid name (files).
Project 'ui-cards-e2e' contains extension with invalid name (files).
Project 'ui-dashboard' contains extension with invalid name (files).
Project 'ui-cards' contains extension with invalid name (files).
Project 'ui-auth' contains extension with invalid name (files).
Project 'ui-main' contains extension with invalid name (files).
[NX] Angular devkit readJsonWorkspace fell back to Nx workspaces logic
Workspace extension with invalid name (pluginsConfig) found.
Project 'shared-root-security-ui-authenticate' contains extension with invalid name (files).
Project 'shared-root-ui-notification' contains extension with invalid name (files).
Project 'shared-root-security-auth' contains extension with invalid name (files).
Project 'shared-root-ui-components' contains extension with invalid name (files).
Project 'shared-root-environment' contains extension with invalid name (files).
Project 'shared-root-animations' contains extension with invalid name (files).
Project 'shared-root-isomorphic' contains extension with invalid name (files).
Project 'shared-root-ui-feature' contains extension with invalid name (files).
Project 'shared-root-constants' contains extension with invalid name (files).
Project 'shared-root-ui-assets' contains extension with invalid name (files).
Project 'shared-root-ui-common' contains extension with invalid name (files).
Project 'shared-root-ui-styles' contains extension with invalid name (files).
Project 'shared-root-logging' contains extension with invalid name (files).
Project 'shared-root-config' contains extension with invalid name (files).
Project 'shared-root-models' contains extension with invalid name (files).
Project 'shared-root-core' contains extension with invalid name (files).
Project 'ui-dashboard-e2e' contains extension with invalid name (files).
Project 'ui-navigation' contains extension with invalid name (files).
Project 'ui-cards-e2e' contains extension with invalid name (files).
Project 'ui-dashboard' contains extension with invalid name (files).
Project 'ui-cards' contains extension with invalid name (files).
Project 'ui-auth' contains extension with invalid name (files).
Project 'ui-main' contains extension with invalid name (files).
[NX] Angular devkit called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
[NX] Angular devkit readJsonWorkspace fell back to Nx workspaces logic
Workspace extension with invalid name (pluginsConfig) found.
Project 'shared-root-security-ui-authenticate' contains extension with invalid name (files).
Project 'shared-root-ui-notification' contains extension with invalid name (files).
Project 'shared-root-security-auth' contains extension with invalid name (files).
Project 'shared-root-ui-components' contains extension with invalid name (files).
Project 'shared-root-environment' contains extension with invalid name (files).
Project 'shared-root-animations' contains extension with invalid name (files).
Project 'shared-root-isomorphic' contains extension with invalid name (files).
Project 'shared-root-ui-feature' contains extension with invalid name (files).
Project 'shared-root-constants' contains extension with invalid name (files).
Project 'shared-root-ui-assets' contains extension with invalid name (files).
Project 'shared-root-ui-common' contains extension with invalid name (files).
Project 'shared-root-ui-styles' contains extension with invalid name (files).
Project 'shared-root-logging' contains extension with invalid name (files).
Project 'shared-root-config' contains extension with invalid name (files).
Project 'shared-root-models' contains extension with invalid name (files).
Project 'shared-root-core' contains extension with invalid name (files).
Project 'ui-dashboard-e2e' contains extension with invalid name (files).
Project 'ui-navigation' contains extension with invalid name (files).
Project 'ui-cards-e2e' contains extension with invalid name (files).
Project 'ui-dashboard' contains extension with invalid name (files).
Project 'ui-cards' contains extension with invalid name (files).
Project 'ui-auth' contains extension with invalid name (files).
Project 'ui-main' contains extension with invalid name (files).
SchematicsException [Error]: Project "shared-root-security-graphql" does not exist.
    at /Users/w509297/PR/150305/Yeti-UI/node_modules/@schematics/angular/component/index.js:32:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

 >  NX   Project "shared-root-security-graphql" does not exist.

   Pass --verbose to see the stacktrace.
`

**Comment by kenatwex** [comment]
okay this has to stop committing code that shuts down the entire product
are we going to get into the webpack npm thing here?

roll whatever was released back and at least get us back to whats working

please

**Comment by Coly010** [comment]
If this is in the `package-based` repo selection, we are investigating it internally and working on the correct solution.

**Comment by Coly010** [comment]
While we continue to work on this, the workaround would be to do the following

1. Add a `tsconfig.base.json` at the root of your workspace with the following contents:

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "esnext",
    "lib": ["es2017", "dom"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "baseUrl": ".",
    "paths": {}
  },
  "exclude": ["node_modules", "tmp"]
}
```

**Comment by zpydee** [comment]
aplogies, i've been away from github for a couple weeks. my tsconfig.base.json has these options with the only difference being the empty path object in yours.  

implementing identically unfortunately yields no solution.

@Coly010  would it be helpful if we had a quick online session to look at my repo together? I unfortunately cannot give access.

**Comment by zpydee** [comment]
@Coly010 I've created a demo repo for you to look at...

https://github.com/zpydee/nx-issue-demo

**Comment by Coly010** [comment]
It looks like this issue has been resolved in latest Nx. 

If you are unable to migrate to latest Nx because you're still on Angular 14 and don't want to migrate to Angular 15, we'll soon be releasing support for Angular 14 + Angular 15 in Nx 15.x. 

That way, you'll be able to migrate to the latest version of Nx without having to migrate Angular

**Comment by zpydee** [comment]
My sincere apologies - when I replicated my repo to demo I made the mistake of using an older branch that was running ng 14.

However, I've now migrated to nx 15.6.3 in my actual repo and I'm still experiencing the same problem.

here's my nx report

```bash
 Node : 16.14.2
   OS   : darwin arm64
   npm  : 8.5.0
   
   nx : 15.6.3
   @nrwl/angular : 15.6.3
   @nrwl/cypress : 15.6.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.3
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : 15.6.3
   @nrwl/next : Not Found
   @nrwl/node : 15.6.3
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.6.3
   @nrwl/workspace : 15.6.3
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @ngrx/component-store: 15.0.0
         @ngrx/effects: 15.0.0
         @ngrx/entity: 15.0.0
         @ngrx/router-store: 15.0.0
         @ngrx/store: 15.0.0
         @ngrx/schematics: 15.0.0
         @ngrx/store-devtools: 15.0.0
         eslint-plugin-ngrx: 2.1.4
```

@Coly010 i think we're in the same time zone. Would you be interested in a quick slack huddle? If not, I can create another empty repo with my "actual" environment and repost?

Thanks in advance for your assistance...

**Comment by Coly010** [comment]
@zpydee I think creating a new repo that replicates your environment would be better, it'll be easier for others to pick up the issue if I can't etc.

**Comment by zpydee** [comment]
Ok, this repo 👇 is now running `15.6.3` with the issue I'm experiencing still occurring

https://github.com/zpydee/nx-issue-sample-repo

**Comment by leosvelperez** [comment]
hey @zpydee!

Thanks for providing a repo where we can reproduce it.

The issue is happening because of an old version of `@angular-devkit/schematics` being hoisted at the root of your `node_modules`:

```
npm ls @angular-devkit/schematics

├─┬ @angular/cli@15.1.2
│ ├── @angular-devkit/schematics@15.1.2
│ └─┬ @schematics/angular@15.1.2
│   └── @angular-devkit/schematics@15.1.2 deduped
├─┬ @angular/fire@7.5.0
│ ├── @angular-devkit/schematics@13.3.9 invalid: "14.2.9" from node_modules/@ngrx/schematics
│ └─┬ @schematics/angular@15.0.1
│   └── @angular-devkit/schematics@15.0.1
├─┬ @angular/pwa@15.0.1
│ └── @angular-devkit/schematics@15.0.1
├─┬ @nestjs/schematics@9.0.3
│ └── @angular-devkit/schematics@14.2.1
├─┬ @ngrx/schematics@15.0.0
│ └── @angular-devkit/schematics@13.3.9 deduped invalid: "14.2.9" from node_modules/@ngrx/schematics
├─┬ @nrwl/angular@15.6.3
│ ├── @angular-devkit/schematics@15.1.2
│ └─┬ @schematics/angular@15.1.2
│   └── @angular-devkit/schematics@15.1.2 deduped
└─┬ eslint-plugin-ngrx@2.1.4
  └── @angular-devkit/schematics@13.3.9 deduped invalid: "14.2.9" from node_modules/@ngrx/schematics

npm ERR! code ELSPROBLEMS
npm ERR! invalid: @angular-devkit/schematics@13.3.9 /Users/leosvel/code/issues/13544-cannot-generate-lib/node_modules/@angular-devkit/schematics

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/leosvel/.npm/_logs/2023-01-31T08_41_52_679Z-debug-0.log
```

**If you set `"@angular-devkit/schematics": "15.1.3"` in your `package.json,` the issue goes away**. Nuking the `node_modules` and deleting your `package-lock.json` should also do the trick, but I recommend doing the former, which is more deterministic.

You have probably ended up in this state because of how `npm` resolves dependencies through time. The lock file is not updated with newer versions of `@angular-devkit/schematics` that those packages can depend on. That's why it should work correctly if you delete the lock file and recreate it by installing it again.

On a separate note, the `eslint-plugin-ngrx` package is deprecated and you should use the `@ngrx/eslint-plugin` package instead. That should remove one package that depends on an old version of `@angular-devkit/schematics`.

**Comment by zpydee** [comment]
Thanks a ton for your speedy response. I'll take a look and let you know if I have any further issues.

If I may ask another quick question....

I notice when I created a fresh nx workspace that `angular.json` as not present anymore. Should I be doing anything on that front in my repo to keep it more aligned with the way fresh workspaces are created?

**Comment by leosvelperez** [comment]
It'll work fine either way, though you can remove it if you want. As you noticed, we don't generate it in new workspaces, because it's no longer required. A migration will remove `angular.json` files with a format version "2" in an upcoming version.
