### ISSUE TITLE
Application build failing after upgrade to 15.4.2

### ISSUE THREAD

**Issue by Blizard** [nrwl/nx#14106]
### Current Behavior

Both dynamic/static application build fail with error after upgrade from `15.0.13` to `15.4.2` using `nx migrate latest`

### Expected Behavior

Both dynamic and static build should pass successfully 

### Steps to Reproduce

1. For now i could not reproduce the problem in new NX repo

### Nx Report

```shell
Node : 16.13.2
   OS   : darwin x64
   yarn : 3.2.0
   
   nx : 15.4.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.4.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.2
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.4.2
   @nrwl/js : 15.4.2
   @nrwl/linter : 15.4.2
   @nrwl/nest : Not Found
   @nrwl/next : 15.4.2
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.4.2
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.4.2
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.4.2
   @nrwl/webpack : 15.4.2
   @nrwl/workspace : 15.4.2
   @nrwl/vite : 15.4.2
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell

> nx run app:build:production

info  - Loaded env from apps/app/.env
info  - Skipping linting
info  - Checking validity of types  
info  - Creating an optimized production build  
info  - Compiled successfully
Warning: You have opted-out of Automatic Static Optimization due to `getInitialProps` in `pages/_app`. This does not opt-out pages with `getStaticProps`
Read more: https://nextjs.org/docs/messages/opt-out-auto-static-optimization

info  - Collecting page data  
Route (pages)                              Size     First Load JS
┌ λ /                                      335 B           326 kB
├   /_app                                  0 B             326 kB
├ λ /404                                   186 B           326 kB
├ λ /...                              1.06 kB         327 kB
├ λ /...                                339 B           326 kB
└ λ /...                                   4.66 kB         331 kB
+ First Load JS shared by all              331 kB
  ├ chunks/framework-66afa89ce7187f6f.js   45.4 kB
  ├ chunks/main-ca9105e8b818c1fc.js        25.7 kB
  ├ chunks/pages/_app-ad0a9e42fc439306.js  252 kB
  ├ chunks/webpack-9cbaf5751fa1a785.js     3.08 kB
  └ css/869f1d99baaa8fef.css               5.09 kB

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)


>  NX   undefined is not iterable (cannot read property Symbol(Symbol.iterator))

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at pruneDependency (.../node_modules/nx/src/lock-file/yarn.js:223:26)
    at .../node_modules/nx/src/lock-file/yarn.js:210:21
    at Array.forEach (<anonymous>)
    at pruneDependencies (.../node_modules/nx/src/lock-file/yarn.js:204:181)
    at pruneYarnLockFile (.../node_modules/nx/src/lock-file/yarn.js:177:32)
    at createLockFile (.../node_modules/nx/src/lock-file/lock-file.js:148:57)
    at .../node_modules/@nrwl/next/src/executors/build/build.impl.js:55:54
    at Generator.next (<anonymous>)
    at fulfilled (.../node_modules/tslib/tslib.js:114:62)
    at runMicrotasks (<anonymous>)


Error: Command failed: nx run app:export
    at checkExecSyncError (node:child_process:826:11)
    at execSync (node:child_process:900:15)
    at createSyncProcess (.../node_modules/nx/src/executors/run-commands/run-commands.impl.js:166:34)
    at .../node_modules/nx/src/executors/run-commands/run-commands.impl.js:113:13
    at Generator.next (<anonymous>)
    at .../node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (.../node_modules/tslib/tslib.js:113:16)
    at runSerially (.../node_modules/nx/src/executors/run-commands/run-commands.impl.js:111:20)
    at .../node_modules/nx/src/executors/run-commands/run-commands.impl.js:52:25 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 83587,
  stdout: null,
  stderr: null
}
```

**Comment by hoonoh** [comment]
This bug seems to be related to versions `15.4.0` and up. 
After rolling back to `15.3.3` everyting seems to be fine.

**Comment by bojanbass** [comment]
I also wanted to say that upgrading NX has been a slight nightmare lately, because after I found this bug I downgraded NX to v.15.3.3, but later developers on the Windows platform were complaining that it's not possible to start or build and app using a custom NX executor. The error from the output was:
```sh
$ nx serve myApp

> NX   Unable to resolve @myOrg/nx-vue:dev-server.

Unable to resolve local plugin with import path @myOrg/nx-vue
```

So it was failing to reference a local plugin on Windows only. It looks like this was fixed in NX v15.4.0, but then the bug from this ticket appeared.

**Comment by jaysoo** [comment]
Is someone willing to share their `yarn.lock` file with me? You can link a gist here or DM it to me https://twitter.com/jay_soo

**Comment by jaysoo** [comment]
We'll disable the lockfile behavior, and do more testing around it. Should be in the next release.

**Comment by jaysoo** [comment]
Merged and will be fixed in 14.4.5.

**Comment by sushruth** [comment]
@jaysoo This is still happening when yarn2+ is used. The problem seems to be that this function - 

https://github.com/nrwl/nx/blob/c3bc51748036dbcc0a3ca52217618667f3e45327/packages/nx/src/lock-file/utils/mapping.ts#L27-L36

checks for existence of a file that may not exist in yarn berry environments. This same function is used here - 

https://github.com/nrwl/nx/blob/c3bc51748036dbcc0a3ca52217618667f3e45327/packages/nx/src/lock-file/yarn.ts#L113-L115

which causes problems in yarn berry environments.

**Comment by anogr** [comment]
I still have the same problem in 15.4.5. We're using pnpm, not yarn.
