### ISSUE TITLE
Nestjs address already in use on restart

### ISSUE THREAD

**Issue by alex-w0** [nrwl/nx#14683]
### Current Behavior

If you create a brand new nx project with the nest preset, if you start the nest app and change a source file to restart the server the following error is shown

Error: listen EADDRINUSE: address already in use :::3333

```
[Nest] 87803  - 01/29/2023, 10:21:12 PM   ERROR [NestApplication] Error: listen EADDRINUSE: address already in use :::3333 +2ms
Error: listen EADDRINUSE: address already in use :::3333
    at Server.setupListenHandle [as _listen2] (node:net:1485:16)
    at listenInCluster (node:net:1533:12)
    at Server.listen (node:net:1621:7)
```

### Expected Behavior

When the nest server restarts, it should wait for the previous process to terminate before attempting to restart the server and should be able to restart on the same port number.

### Steps to Reproduce

1. Create a new nest project using nx
```
npx create-nx-workspace my-workspace --preset=nest

 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Application name                      · test
✔ Enable distributed caching to make your CI faster · Yes

 >  NX   Nx is creating your v15.4.1 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "npm install" several times. Please wait.

✔ Installing dependencies with npm
✔ Nx has successfully created the workspace: my-workspace.
✔ NxCloud has been set up successfully

 >  NX   Successfully initialized git.


 >  NX   Distributed caching via Nx Cloud has been enabled
...
```

3. Change directory to the project
4. Start nest server `nx run test:serve`
6. Make a change to the source file
7. The following error is shown
```
[Nest] 87803  - 01/29/2023, 10:21:12 PM   ERROR [NestApplication] Error: listen EADDRINUSE: address already in use :::3333 +2ms
Error: listen EADDRINUSE: address already in use :::3333
    at Server.setupListenHandle [as _listen2] (node:net:1485:16)
    at listenInCluster (node:net:1533:12)
    at Server.listen (node:net:1621:7)
```

### Nx Report

```shell
nx report

 >  NX   Report complete - copy this into the issue template

   Node : 18.12.1
   OS   : linux x64
   npm  : 8.19.2
   
   nx : 15.4.1
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.1
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.4.1
   @nrwl/js : 15.4.1
   @nrwl/linter : 15.4.1
   @nrwl/nest : 15.4.1
   @nrwl/next : Not Found
   @nrwl/node : 15.4.1
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.4.1
   @nrwl/workspace : 15.4.1
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Additional Information

Same issue as in [#14006](https://github.com/nrwl/nx/issues/14006), which was already closed.

**Comment by AgentEnder** [comment]
@nartc @ndcunningham can one of yall take a look at this?

**Comment by deegansiwicki** [comment]
Update Nx. This has been fixed.

**Comment by alex-w0** [comment]
Sorry I didn't realize that this report was produced with an old version, but I definitely got the same error on my newer project with version 15.6.3. I made a reproduction link: https://github.com/alex-w0/nx-demo

```
npx nx report

 >  NX   Report complete - copy this into the issue template

   Node : 18.13.0
   OS   : linux x64
   npm  : 8.19.3
   
   nx : 15.6.3
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.3
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : 15.6.3
   @nrwl/next : Not Found
   @nrwl/node : 15.6.3
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.6.3
   @nrwl/workspace : 15.6.3
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

I installed Puppeteer, the script (app.service.ts) failed, I made a change to the code and the server throws the error.

```
[Nest] 40185  - 01/30/2023, 8:06:55 AM     LOG [NestFactory] Starting Nest application...
[Nest] 40185  - 01/30/2023, 8:06:55 AM     LOG [InstanceLoader] AppModule dependencies initialized +35ms
[Nest] 40185  - 01/30/2023, 8:06:55 AM     LOG [RoutesResolver] AppController {/api}: +2ms
[Nest] 40185  - 01/30/2023, 8:06:55 AM     LOG [RouterExplorer] Mapped {/api, GET} route +3ms
[Nest] 40185  - 01/30/2023, 8:06:55 AM     LOG [NestApplication] Nest application successfully started +2ms
[Nest] 40185  - 01/30/2023, 8:06:55 AM     LOG 🚀 Application is runninasdfdsag23432 on: http://localhost:3333/api
No errors found.
[Nest] 40185  - 01/30/2023, 8:07:33 AM   ERROR [ExceptionsHandler] Waiting for selector `.search-box__link` failed: Waiting failed: 30000ms exceeded
TimeoutError: Waiting for selector `.search-box__link` failed: Waiting failed: 30000ms exceeded
    at Timeout.<anonymous> (/home/alex/Documents/test/node_modules/puppeteer-core/src/common/WaitTask.ts:80:11)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
assets by status 0 bytes [cached] 1 asset
asset main.js 6.33 KiB [emitted] (name: main) 1 related asset
cached modules 2.58 KiB [cached] 8 modules
./src/app/app.service.ts 1.37 KiB [built] [code generated]
webpack 5.75.0 compiled successfully in 68 ms
Type-checking in progress...
Starting inspector on localhost:9229 failed: address already in use
No errors found.
[Nest] 41338  - 01/30/2023, 8:07:55 AM     LOG [NestFactory] Starting Nest application...
[Nest] 41338  - 01/30/2023, 8:07:55 AM     LOG [InstanceLoader] AppModule dependencies initialized +33ms
[Nest] 41338  - 01/30/2023, 8:07:55 AM     LOG [RoutesResolver] AppController {/api}: +3ms
[Nest] 41338  - 01/30/2023, 8:07:55 AM     LOG [RouterExplorer] Mapped {/api, GET} route +3ms
[Nest] 41338  - 01/30/2023, 8:07:55 AM     LOG [NestApplication] Nest application successfully started +1ms
[Nest] 41338  - 01/30/2023, 8:07:55 AM   ERROR [NestApplication] Error: listen EADDRINUSE: address already in use 127.0.0.1:3333 +5ms
Error: listen EADDRINUSE: address already in use 127.0.0.1:3333
    at Server.setupListenHandle [as _listen2] (node:net:1733:16)
    at listenInCluster (node:net:1781:12)
    at GetAddrInfoReqWrap.doListen (node:net:1930:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:8)
```

**Comment by alex-w0** [comment]
Were you able to reproduce the problem? Do you need additional information?

**Comment by nartc** [comment]
@alex-w0 sorry for the late response. I just checked this with the latest version of Nx and it seems to be working fine. Can you double check? 

PS: `puppeteer` won't launch for me in any case so I changed it to returning a string to test.

**Comment by alex-w0** [comment]
@nartc Hi thanks for your response. Unfortunately the problem still persists for me, and in my opinion it only occurs in combination with Puppeteer, if I just throw a normal error in my application it works fine. 

So I will try to describe the steps to reproduce the problem in more detail. I have now also reworked the demo project, so please pull from the repository again and follow these steps (somehow a folder `assets` was missing in the demo project, I don't know why.... but now it should work to start the server as usual)


1. Clone the demo repo from [`https://github.com/alex-w0/nx-demo`](https://github.com/alex-w0/nx-demo)
2. Go the project `cd nx-demo` and install the dependencies `npm i`
3. Check the version to verify that we are both running on version 15.6.3 `npx nx report`
```
>  NX   Report complete - copy this into the issue template

   Node : 18.12.1
   OS   : linux x64
   npm  : 8.19.2
   
   nx : 15.6.3
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.3
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : 15.6.3
   @nrwl/next : Not Found
   @nrwl/node : 15.6.3
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.6.3
   @nrwl/workspace : 15.6.3
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

4. Start the nestjs server `nx run test:serve`. This should give the following output in the console:
```
> nx run test:serve

asset main.js 6.78 KiB [emitted] (name: main) 1 related asset
asset assets/.gitkeep 0 bytes [emitted] [from: src/assets/.gitkeep] [copied]
cacheable modules 4.2 KiB
  ./src/main.ts 900 bytes [built] [code generated]
  ./src/app/app.module.ts 558 bytes [built] [code generated]
  ./src/app/app.controller.ts 1.37 KiB [built] [code generated]
  ./src/app/app.service.ts 1.41 KiB [built] [code generated]
modules by path external "@nestjs/ 126 bytes
  external "@nestjs/common" 42 bytes [built] [code generated]
  external "@nestjs/core" 42 bytes [built] [code generated]
  external "@nestjs/platform-fastify" 42 bytes [built] [code generated]
external "tslib" 42 bytes [built] [code generated]
external "puppeteer" 42 bytes [built] [code generated]
webpack 5.75.0 compiled successfully in 325 ms
Debugger listening on ws://localhost:9229/bd027dfe-6929-43f2-84af-b59ac8b9c978
For help, see: https://nodejs.org/en/docs/inspector
Type-checking in progress...
[Nest] 44303  - 02/23/2023, 8:14:41 PM     LOG [NestFactory] Starting Nest application...
[Nest] 44303  - 02/23/2023, 8:14:41 PM     LOG [InstanceLoader] AppModule dependencies initialized +35ms
[Nest] 44303  - 02/23/2023, 8:14:41 PM     LOG [RoutesResolver] AppController {/api}: +2ms
[Nest] 44303  - 02/23/2023, 8:14:41 PM     LOG [RouterExplorer] Mapped {/api/working, GET} route +4ms
[Nest] 44303  - 02/23/2023, 8:14:41 PM     LOG [RouterExplorer] Mapped {/api/not-working, GET} route +1ms
[Nest] 44303  - 02/23/2023, 8:14:41 PM     LOG [NestApplication] Nest application successfully started +2ms
[Nest] 44303  - 02/23/2023, 8:14:41 PM     LOG 🚀 Application is running on: http://localhost:3333/api
No errors found.
```

**I have now created two endpoints, one controller contains a working example with Puppeteer and the other gives an error because it could not find the query selector on the page.**

5. Call the endpoint `http://localhost:3333/api/working` and check the output on the server console. You should see the message: `Placeholder text is: Search docs, blogs and more`
```
Type-checking in progress...
[Nest] 44303  - 02/23/2023, 8:14:41 PM     LOG [NestFactory] Starting Nest application...
[Nest] 44303  - 02/23/2023, 8:14:41 PM     LOG [InstanceLoader] AppModule dependencies initialized +35ms
[Nest] 44303  - 02/23/2023, 8:14:41 PM     LOG [RoutesResolver] AppController {/api}: +2ms
[Nest] 44303  - 02/23/2023, 8:14:41 PM     LOG [RouterExplorer] Mapped {/api/working, GET} route +4ms
[Nest] 44303  - 02/23/2023, 8:14:41 PM     LOG [RouterExplorer] Mapped {/api/not-working, GET} route +1ms
[Nest] 44303  - 02/23/2023, 8:14:41 PM     LOG [NestApplication] Nest application successfully started +2ms
[Nest] 44303  - 02/23/2023, 8:14:41 PM     LOG 🚀 Application is running on: http://localhost:3333/api
No errors found.
Placeholder text is: Search docs, blogs and more
```

6. Now let's call the not working endpoint `http://localhost:3333/api/not-working` and inspect the server console again. You should see the following error
```
[Nest] 44303  - 02/23/2023, 8:16:17 PM   ERROR [ExceptionsHandler] Error: failed to find element matching selector ".search-box__input_NOT_EXIST"
Error: Error: failed to find element matching selector ".search-box__input_NOT_EXIST"
    at ElementHandle.$eval (./nx-demo/node_modules/puppeteer-core/src/common/ElementHandle.ts:194:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

7. Go to the `app.service.ts` file and change the console log from line 29 to the following (or just make any change in the file)
```
    console.log("Placeholder text is not working: " + placeholderText);
```
Nestjs now tries to restart the server and gives the following error message that the port is already in use.
```
[Nest] 45012  - 02/23/2023, 8:17:31 PM     LOG [RouterExplorer] Mapped {/api/working, GET} route +3ms
[Nest] 45012  - 02/23/2023, 8:17:31 PM     LOG [RouterExplorer] Mapped {/api/not-working, GET} route +1ms
[Nest] 45012  - 02/23/2023, 8:17:31 PM     LOG [NestApplication] Nest application successfully started +2ms
[Nest] 45012  - 02/23/2023, 8:17:31 PM   ERROR [NestApplication] Error: listen EADDRINUSE: address already in use 127.0.0.1:3333 +4ms
Error: listen EADDRINUSE: address already in use 127.0.0.1:3333
    at Server.setupListenHandle [as _listen2] (node:net:1485:16)
    at listenInCluster (node:net:1533:12)
    at GetAddrInfoReqWrap.doListen (node:net:1682:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:8)
```

Let me know if this helps, thanks :)

**Comment by nartc** [comment]
@alex-w0 thank you for the detailed answer. We kinda found the issue but still thinking of a fix for it.

The issue has to do with Node's `ChildProcess`. 
- `@nrwl/js:node` forks a child process to run a monkey-patched version `node .` to handle Path Mappings (aka resolving path aliases)
- `puppeteer` probably spawns its own child processes to `launch` and all that. 

When the child process (that `puppeteer` spawns) throws an error, something causes the forked process of `nrwl/js:node` to not terminate properly.

From the consumer side of things (your application), if you wrap the code that throws the error and close the `puppeteer` process, then everything works as expected

```ts
    try {
      const placeholderText = await page.$eval(
        ".search-box__input_NOT_EXIST",
        (el) => el.getAttribute("placeholder")
      );

      console.log("Placeholder text is: " + placeholderText);
    } catch (e) {
      // close the browser process here
      await browser.close();
      // then rethrow the error for Nest's ExceptionHandler
      throw e;
    }
```

Another fix would be in `js:node` itself but I'm not sure of the fix just yet so I'll need to circle back to this issue at a later time. Hopefully the `try/catch` workaround unblocks you for now.

**Comment by alex-w0** [comment]
Great that you were able to reproduce it now. Your explanation seems reasonable that this is the problem.

I can definitely use your proposed solution to solve my problem for now. Thank you

**Comment by nartc** [comment]
@alex-w0 Glad the workaround worked for you. We've discussed this internally and decided not to move forward with the fix inside of `js:node` as we're not sure if the fix actually fixes the issue. This seems to us that this is a 3rd party issue and we have a workaround so I'll be closing this. If you have further questions/issues, please open a new one.
