### ISSUE TITLE
React lib with Vite is not exporting types

### ISSUE THREAD

**Issue by gperdomor** [nrwl/nx#15181]
### Current Behavior

I'm building a chakra-ui based library and I'm trying to re-export some components, like buttons...

When I build the lib with rollup and install it in other project, component props are handled fine by vscode
<img width="1048" alt="Screenshot 2023-02-22 at 2 55 54 PM" src="https://user-images.githubusercontent.com/371939/220732994-e57a6839-60c7-4aff-87ed-c3f865ea679d.png">

But, when I build the lib with vite and install it in other project, component props are not detected and vscode only shows `key`

<img width="1028" alt="Screenshot 2023-02-22 at 2 51 29 PM" src="https://user-images.githubusercontent.com/371939/220733247-a02effca-cb57-43ca-84b0-d8f467522b5a.png">

### Expected Behavior

I both cases vscode should be able to show the props

### GitHub Repo

https://github.com/gperdomor/nx-vite-types-issue

### Steps to Reproduce

1. Clone this https://github.com/gperdomor/nx-vite-types-issue - This repo has two libraries lib-rollup and lib-vite, both libs has and index.ts file where I'm reexporting the chakra button and props.
2. Build the libs and run `npm pack dist/packages/*`
3. Create a react project using `create-react-app` cli
4. Install `lib-vite` or `lib-rollup` from the packaged tgz
5. Try to use the button and press CMD+Space or Ctrl+Space to get the props list

### Nx Report

```shell
Node : 18.14.1
   OS   : darwin x64
   npm  : 9.5.0
   
   nx                      : 15.7.2
   @nrwl/jest              : 15.7.2
   @nrwl/linter            : 15.7.2
   @nrwl/workspace         : 15.7.2
   @nrwl/cli               : 15.7.2
   @nrwl/devkit            : 15.7.2
   @nrwl/eslint-plugin-nx  : 15.7.2
   @nrwl/js                : 15.7.2
   @nrwl/react             : 15.7.2
   @nrwl/rollup            : 15.7.2
   @nrwl/tao               : 15.7.2
   @nrwl/vite              : 15.7.2
   typescript              : 4.8.4
```

**Comment by mandarini** [comment]
Hi there @gperdomor ! Can you please take a look at this documentation: https://nx.dev/packages/vite/documents/set-up-vite-manually#dts-plugin

And also this issue: https://github.com/nrwl/nx/issues/14955#issuecomment-1428562452

And let me know if your issue is resolved!

**Comment by gperdomor** [comment]
@mandarini not working for me :(... Same results, I only see the `key` in the prop list

**Comment by mandarini** [comment]
Ah I see. Your `lib-vite` is not building. When I try to build, I see the following error:

```
[vite]: Rollup failed to resolve import "framer-motion" from "/Users/katerina/Projects/nrwl/test_nx_workspaces/nx-vite-types-issue/node_modules/@chakra-ui/checkbox/dist/chakra-ui-checkbox.esm.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```

This is not related to Nx. Please take a look at this issue: https://github.com/chakra-ui/chakra-ui/issues/3618

There seems to be a problem with chakra-ui and framer-motion. Since your library does not build, then it makes sense that it's not working correctly. Please try to fix the build first!

**Comment by mandarini** [comment]
Hm actually the build is fixed when I add `framer-motion`. `yarn add -D framer-motion`. So, your build succeeds?

**Comment by mandarini** [comment]
Ok, yeah, I followed your steps exactly, and I get a whole list of props. So, I must assume it's your broken build.


<img width="879" alt="Screenshot 2023-02-23 at 2 36 50 PM" src="https://user-images.githubusercontent.com/6603745/220907712-28580d89-a8df-4aba-8a37-3650c32357ef.png">
<img width="883" alt="Screenshot 2023-02-23 at 2 36 44 PM" src="https://user-images.githubusercontent.com/6603745/220907717-049a490b-ccc2-4f96-809d-295b5c92f5a3.png">

**Comment by mandarini** [comment]
So, my steps were:

1. Clone your repo
2. `cd` in your repo
3. `yarn add -D framer-motion` which gives me version `"^9.1.1"`
4. `yarn` to install all deps
5. `npx nx run-many --target=build --parallel=true --skipNxCache` to build both libraries
6. `npm pack dist/packages/*`
7. Change dir
8. `npx create-react-app@latest my-app --template typescript`
9. Copy the `.tgz` files there
10. `npm install sandbox-lib-rollup-0.0.1.tgz`
11. `npm install sandbox-lib-vite-0.0.5.tgz`
12. Use `Button` in `App.tsx`
13. See above screenshot

**Comment by gperdomor** [comment]
@mandarini the idea is install only the vite build, not both of them... I install framer-motion but I'm still seeing the same results (no props using lib-vite)...

<img width="609" alt="Screenshot 2023-02-23 at 2 28 46 PM" src="https://user-images.githubusercontent.com/371939/220984023-ee60b0e3-8871-4bc3-9d4c-732500a8248f.png">

**Comment by mandarini** [comment]
Hmm interesting. I don't see how building both vs building only one wpuld make a difference.

**Comment by mandarini** [comment]
Hmm interesting. I don't see how building both vs building only one wpuld make a difference. If you build both of them, do you get the props?

**Comment by gperdomor** [comment]
I mean, If I install both or only the rollup version, I get the props...

Both libs expose the same button, the only change is the bundler

**Comment by mandarini** [comment]
@gperdomor Ok I managed to reproduce! Thank you for the info! 
Are you sure this error is on the Nx side? Have you tried this on a non-Nx setting? I cannot see how Nx plays a role here, this sounds like a Vite issue, unfortunately,.
