### ISSUE TITLE
Multiple issues running `@nx/js:node` executor (entry file must be named main.ts)

### ISSUE THREAD

**Issue by ajwootto** [nrwl/nx#17595]
### Current Behavior

On this repository where we're using Nx 14.7.11
https://github.com/DevCycleHQ/js-sdks/tree/8ae38756b1494bf007147480c45693140a141cd6

We have a project named `shared-bucketing-test-data` located in `lib/shared/bucketing-test-data` which is essentially a node script that generates some test data.
It runs using the command `nx build:json shared-bucketing-test-data` and everything works on this version of Nx. The "build" target is configured to use `@nx/js:tsc` and the `build:json` target runs the built output using the `@nx/node:node` executor.

In this commit, I've updated to Nx 16.3.2
https://github.com/DevCycleHQ/js-sdks/tree/e29999ddeddf940dde7ee76feb6097d72ee35822

Now the same `build:json` target no longer executes the Node script defined by this project. The command executes "successfully" with no errors, but also does not actually run the script.

To try and fix it,  I generated a new `@nx/node:application` to see what the latest setup should be for a Node application. The generator now uses `esbuild` and switched from `@nx/node:node` to `@nx/js:node`, so I copied that configuration to my existing project. 

That did not fix the problem, it exhibited the same behaviour of "running successfully" without actually running.

Then I renamed the `index.ts` file to `main.ts` and now the script executes successfully. If I name it anything else, it doesn't work.

This file rename fixed the build for the `esbuild` setup, but applying the same change to my original `tsc` setup did not fix the problem.

It also seems like any errors thrown by the script are being swallowed, so even when the script does run I'll see logs up until an error is thrown, and then nothing that reflects the error (just a clean exist with a "success" from nx)

The final version which fixes the configuration issues is here
https://github.com/DevCycleHQ/js-sdks/tree/889001dc8a435202e5487bca0bc1956660b77463

To summarize, I had to switch from using `@nx/js:tsc` to `@nx/esbuild:esbuild` to build. I also had to make my main file named `main.ts` and not `index.ts` or anything else besides `main.ts`. Finally, the script was also throwing an unrelated error which was never being logged (and still isn't).

### Expected Behavior

- my existing setup should keep working (as far as I can tell) in newer Nx version. I could not get the setup to work at all while using the `@nx/web:tsc` executor to build my files
- the `@nx/web:node` executor should not require the main file to be named `main.ts` (as seems to be the case)
- errors should be logged correctly when thrown by the script being executed

### GitHub Repo

https://github.com/DevCycleHQ/js-sdks/tree/e29999ddeddf940dde7ee76feb6097d72ee35822

### Steps to Reproduce

1. Clone sample repository, run yarn
2. `yarn nx build:json shared-bucketing-test-data --skip-nx-cache`
3. Command completes successfully with no errors, but script does not run (no logs)

### Nx Report

```shell
Node   : 18.16.0
   OS     : darwin arm64
   yarn   : 3.2.0
   Hasher : Native

   nx                 : 16.3.2
   lerna              : 5.6.2
   @nx/js             : 16.3.2
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nx/workspace      : 16.3.2
   @nx/cypress        : 16.3.2
   @nx/detox          : 16.3.2
   @nx/devkit         : 16.3.2
   @nx/esbuild        : 16.3.2
   @nx/eslint-plugin  : 16.3.2
   @nx/next           : 16.3.2
   @nx/node           : 16.3.2
   @nx/react          : 16.3.2
   @nx/react-native   : 16.3.2
   @nx/rollup         : 16.3.2
   @nrwl/tao          : 16.3.2
   @nx/web            : 16.3.2
   @nx/webpack        : 16.3.2
   typescript         : 5.0.4
   ---------------------------------------
   Local workspace plugins:
   	 @devcycle/bucketing-assembly-script
   	 @devcycle/openfeature-nodejs-provider
   	 @devcycle/bucketing-test-data
   	 @devcycle/bucketing
   	 @devcycle/devcycle-react-native-sdk
   	 @devcycle/types
   	 @devcycle/nodejs-server-sdk
   	 @devcycle/devcycle-react-sdk
   	 @devcycle/devcycle-js-sdk
```
```


### Failure Logs

_No response_

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

**Comment by mandarini** [comment]
Hi @ajwootto ! Can you please try using Nx version `16.4.0-beta.6`? We fixed a number of things on the `@nx/js:node` executor in these last releases.

**Comment by ajwootto** [comment]
@mandarini I'd rather wait for the full release before trying any beta versions to be honest, this migration has been extremely painful so far (spent many days on it working around a bunch of Nx issues with migrations ,executors etc.)

Also what's the difference between `@nx/node:node` and `@nx/js:node` and which one should be used now?

**Comment by mandarini** [comment]
I'll look into your issue tomorrow, more. In the meantime, I created [this PR](https://github.com/DevCycleHQ/js-sdks/pull/506), where I migrated your repo from `14.7.11` to `16.4.0-beta.6`. Can you please check it out and tell me if it solves your issue?

**Comment by ajwootto** [comment]
@mandarini thanks for setting that up, I just tried it on the `next` version branch.

It seems that all the issues I was seeing are still happening. In the `main.ts` file for the `shared-bucketing-test-data` project:
https://github.com/DevCycleHQ/js-sdks/pull/507/files#diff-16ba0071f7889f344e90958c6813ea89c2e2d810c3d3008203abc76d0b39a387

- if I deliberately throw an error from the script, it isn't logged and command completes successfully
- if I rename the `main.ts` file to `index.ts`, it no longer runs

**Comment by mandarini** [comment]
@ajwootto 

Using the code on my PR linked above and running: `npx nx build:json shared-bucketing-test-data --skipNxCache` the results are:

* I do get the logs, but indeed the error I add is not thrown. Here's the output on my machine: https://app.warp.dev/block/BgtkHZ5Tty9yrErDqFcDaN
* If I run the script from the dist folder, the error is thrown as expected, that is if I run `node dist/lib/shared/bucketing-test-data/main.js` the output is: https://app.warp.dev/block/1wpoH1MrgBM2D6EWOHfC9D

If I change the name of `main.ts` to `index.ts` the result is the same. Make sure you change the path to `main` in your `build` target in `lib/shared/bucketing-test-data/project.json`, as I have done in my PR, too. Here's the result:

https://app.warp.dev/block/8KwxPreITlHwEC2OXgRN3V

**Comment by ajwootto** [comment]
Hey @mandarini, thanks for the detailed investigation!

I can confirm the following:
- error is swallowed as you describe
- error is thrown properly in watch mode
- error is thrown when running script directly from `dist/

I can also confirm that adding the `outputFileName` setting to the build target allows the script to run, without that setting it doesn't (even if the main option is set correctly)

 I see in the docs for that option that it's supposed to default to the same "base name" as the main file:https://nx.dev/packages/esbuild/executors/esbuild#outputfilename
 
 in that case is it defaulting to `index.ts` rather than `index.js` or something? That wouldn't explain why it works with `main.ts` being the main file while not having this option specified, so I assume it's not defaulting correctly.
 
 That option is also not present in the `js:tsc` executor. Does that mean I can't use that executor to build my node files while running it with `js:node`?
 
 I also would consider it a bug that the executor didn't throw an error of some kind when the expected outputFileName wasn't found during execution, since there's no other way to tell what the problem is here. Maybe that is happening and it's getting swallowed by the existing "error isn't thrown" issue?

Maybe there should also be a migration or warning during the upgrade that the build target needs to be fixed for "node" executor to keep working?
 
 Finally, if you generate a new `node` application, by default the `project.json` configuration does not include the `outputPathName` option. Thus I'd imagine anyone starting from a new node application and deciding to rename their entrypoint file would run into this issue (even if they correctly change the `main` option).

**Comment by mandarini** [comment]
1. I put a PR in to always log the error
2. I will make sure we infer the name from `main`, as it says in the docs

For the rest, let me think a bit! :)
