### ISSUE TITLE
npm install does not install optional dependencies

### ISSUE THREAD

**Issue by kamathgopal** [nrwl/nx#20088]
### Current Behavior

We are building an application using lerna monorepo. The build on azure pipeline is failing due to the absence of package @nx/nx-linux-x64-gnu. We use Mac M1 chip machines to build locally and linux machine to build on pipeline. If we delete the package-lock from repo pipeline build will be successful but we maintain package-lock in our repo as team's best practice. Is there any way to fix this issue?

### Expected Behavior

Optional dependencies to be installed and build be successful

### Steps to Reproduce

1. use lerna version 7.1.5
2. run npm install on Mac M1 chip
3. commit package-lock
4. checkout code on linux (ubuntu) machine
5. run npm install
6. npm run build

### Nx Report

```shell
NA
```

### Failure Logs

```shell
Error: Cannot find module '@nx/nx-linux-x64-gnu'
Require stack:
- /agent/_work/1/s/node_modules/nx/src/native/index.js
- /agent/_work/1/s/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js
- /agent/_work/1/s/node_modules/nx/src/config/workspaces.js
- /agent/_work/1/s/node_modules/@nx/devkit/nx-reexports-pre16.js
- /agent/_work/1/s/node_modules/@nx/devkit/index.js
- /agent/_work/1/s/node_modules/lerna/dist/index.js
- /agent/_work/1/s/node_modules/lerna/dist/cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/agent/_work/1/s/node_modules/nx/src/native/index.js:184:31)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/agent/_work/1/s/node_modules/nx/src/native/index.js',
    '/agent/_work/1/s/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js',
    '/agent/_work/1/s/node_modules/nx/src/config/workspaces.js',
    '/agent/_work/1/s/node_modules/@nx/devkit/nx-reexports-pre16.js',
    '/agent/_work/1/s/node_modules/@nx/devkit/index.js',
    '/agent/_work/1/s/node_modules/lerna/dist/index.js',
    '/agent/_work/1/s/node_modules/lerna/dist/cli.js'
  ]
}
```

### Operating System

- [X] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by marko-hologram** [comment]
I cannot find the exact issue now on GitHub where I saw something similar, but I believe it was resolved by declaring these packages as `optionalDependencies` in package.json:

```json
"optionalDependencies": {
    "@nx/nx-darwin-arm64": "17.0.3",
    "@nx/nx-darwin-x64": "17.0.3",
    "@nx/nx-linux-x64-gnu": "17.0.3",
    "@nx/nx-win32-x64-msvc": "17.0.3",
}
```

Then when running `npm install`, it should automatically install one of these depending on the platform where it's running.

I specified these all as v17.0.3 because that's the latest, but if that doesn't work maybe try latest 16.x (16.10.0). I never used Lerna, but I know NX team took over the project so I guess Lerna depends on something in NX so that's part of the reason you are getting this error.

As for the exact reason why this happens, I'm not sure, but there are some troubleshooting steps listed in NX docs https://nx.dev/recipes/troubleshooting/troubleshoot-nx-install-issues#how-to-fix

**Comment by ghenadiibatalski** [comment]
Any update on it? Makes work on angular 17 impossible somehow

**Comment by Martinspire** [comment]
I'm having the same issue using `npm ci` on github actions.

Suddenly out of nowhere on a branch that didn't even change the package.json

**Comment by MaxKless** [comment]
It might be due to this npm issue as well: https://github.com/npm/cli/issues/4828
@kamathgopal can you confirm that you've gone through the troubleshooting steps and that this issue is still happening?

**Comment by jasonfutch** [comment]
Adding this optional dependencies fixed it for me..

  "optionalDependencies": {
    "@esbuild/darwin-arm64": "^0.24.0",
    "@nx/nx-darwin-arm64": "^20.1.0",
    "@nx/nx-darwin-x64": "^20.1.0",
    "@nx/nx-linux-x64-gnu": "^20.1.0",
    "@nx/nx-win32-x64-msvc": "^20.1.0",
    "@swc/core-darwin-arm64": "^1.9.2",
    "@swc/core-darwin-x64": "^1.9.2",
    "@swc/core-linux-arm-gnueabihf": "^1.9.2",
    "@swc/core-linux-arm64-gnu": "^1.9.2",
    "@swc/core-linux-arm64-musl": "^1.9.2",
    "@swc/core-linux-x64-gnu": "^1.9.2",
    "@swc/core-linux-x64-musl": "^1.9.2",
    "@swc/core-win32-arm64-msvc": "^1.9.2",
    "@swc/core-win32-ia32-msvc": "^1.9.2",
    "@swc/core-win32-x64-msvc": "^1.9.2"
  }

npm install @swc/core-darwin-arm64 @swc/core-darwin-x64 @swc/core-linux-arm-gnueabihf @swc/core-linux-arm64-gnu @swc/core-linux-arm64-musl @swc/core-linux-x64-gnu @swc/core-linux-x64-musl @swc/core-win32-arm64-msvc @swc/core-win32-ia32-msvc @swc/core-win32-x64-msvc @esbuild/darwin-arm64 @nx/nx-darwin-arm64 @nx/nx-darwin-x64 @nx/nx-linux-x64-gnu @nx/nx-win32-x64-msvc --save-optional
