### ISSUE TITLE
NX creates complete mess of Jest configurations

### ISSUE THREAD

**Issue by SachinShekhar** [nrwl/nx#2506]
To start with, NX's Jest configurations aren't in adherence with Jest's official documentation. I understand that NX has custom test builders and then there are e2e tests using them. So, I won't complain about it.

## My complaint
If Jest configs are wrong, why does NX write them into `jest.config.js` files?

## My problem:
Because of wrong config, Jest CLI (which is way faster than `ng test`) as well as any IDE extensions (like Wallaby.js) depending on it malfunction. When I try to edit those config files to make them work with Jest CLI, `ng test` fails.

## How I solved the issue:
I renamed all `jest.config.ts` files to `nx.jest.config.ts` and updated their paths in `angular.json` and apps/ libs specific config files (preset paths). Then, I also configured Jest for Jest CLI myself. This way both Jest CLI and `ng test` work.

Unfortunately, I need to do this everytime I create apps/ libs using NX. And, NX update might break everything again.

## My suggestion:
Don't write NX's Jest configs into `jest.config.ts`. Use a different filename. It'd also be nice if you also config Jest for Jest CLI.

**Comment by jaysoo** [comment]
@SachinShekhar Thanks for reporting this issue. What do you mean by the config being invalid, do you have an example repo for this?

From what I can tell, we were using the invalid `passWithNoTest` option, which results in a warning from Jest. This issue has been fixed here: https://github.com/nrwl/nx/pull/2442

**Comment by SachinShekhar** [comment]
@jaysoo Yes, my original repo has `passWithNoTest` in jest.config.js, but even after removing this line, the issues persisted with new nasty error. BTW, I just created a new repo: https://github.com/SachinShekhar/nx-jest-config-bug

Jest CLI (and dependent IDE extension) support is not out-of-box. When I ran `ng add @nrwl/jest`, it didn't replace `karma` config of existing app with `jest`. I don't know if it's bug or not, but it's enough to make `Wallaby.js` useless because it supports only one type of test runner in a repo.

I also created a new lib named `website` (it is configured with Jest). If you run `ng test website`, all tests will pass. But, if you run `npx jest --rootDir=libs/website`, all tests will fail throwing some nasty errors. To fix this, I need to poke into existing `jest.cong.js` files which might break a working solution (which is what exactly happened with my original repo).

**Comment by jaysoo** [comment]
@SachinShekhar I would suggest updating to `9.0.2` to remove the warning.

You will also need to inline the following in your root `jest.config.js` file (Nx adds these automatically when running the Jest builder).

```
      stringifyContentPathRegex: '\\.(html|svg)$',
      astTransformers: [
        'jest-preset-angular/build/InlineFilesTransformer',
        'jest-preset-angular/build/StripStylesTransformer'
      ]
```

In the future we will probably just inline all of the generated config so users have more control over what is used.

**Note:** We don't currently guarantee that standalone Jest can be used without some modifications. If you are concerned about the default generated files from Nx schematics, it might be useful to wrap them in a workspace schematic and modify the files as you see fit: https://nx.dev/angular/guides/workspace-schematics.

Going to close this issue since there are workarounds, and no concrete action that we can take right now.
