### ISSUE TITLE
Cloud agent crashing when new caching is enabled

### ISSUE THREAD

**Issue by tmercswims** [nrwl/nx#28806]
### Current Behavior

After upgrading to Nx 20 (from 19), and enabling the new database-based caching by removing the `useLegacyCache` flag from my `nx.json`, most (but not all) of my CIPE runs are failing with error that look like this:

> Agent 'job-67292d4f767f6f3d87a1cbad-0-agent-2' exited with the error: Missing field `code`.

One of my team members was able to reproduce this issue locally, and when running with `--verbose` he obtained the following stack trace:

```
Error: Missing field `code`
    at DbCache.applyRemoteCacheResults (.../node_modules/nx/src/tasks-runner/cache.js:80:27)
    at DbCache.get (.../node_modules/nx/src/tasks-runner/cache.js:65:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TaskOrchestrator.applyCachedResult (.../node_modules/nx/src/tasks-runner/task-orchestrator.js:131:30)
    at async Promise.all (index 0)
    at async TaskOrchestrator.applyCachedResults (.../node_modules/nx/src/tasks-runner/task-orchestrator.js:126:21)
    at async TaskOrchestrator.applyFromCacheOrRunTask (.../node_modules/nx/src/tasks-runner/task-orchestrator.js:219:40)
    at async TaskOrchestrator.executeNextBatchOfTasksUsingTaskSchedule (.../node_modules/nx/src/tasks-runner/task-orchestrator.js:85:13)       
    at async Promise.all (index 2)
    at async TaskOrchestrator.run (.../node_modules/nx/src/tasks-runner/task-orchestrator.js:61:9)
```

This was with Nx 20.0.7, but as I said, it seems to be somewhat intermittent. Some of our CIPE runs went just fine, but many failed. Adding `useLegacyCache: true` back into the `nx.json` stopped this issue completely, so it appears to be related to the new caching.

I also have a support ticket open which contains more information, including a link to a CIPE.

### Nx Report

Node           : 22.11.0
yarn           : 4.5.1

nx                 : 20.0.7
@nx/js             : 20.0.7
@nx/jest           : 20.0.7
@nx/eslint         : 20.0.7
@nx/workspace      : 20.0.7
@nx/angular        : 20.0.7
@nx/devkit         : 20.0.7
@nx/eslint-plugin  : 20.0.7
@nx/nest           : 20.0.7
@nx/node           : 20.0.7
@nx/web            : 20.0.7
@nx/webpack        : 20.0.7
typescript         : 5.4.5

### Package Manager Version

yarn 4.5.1

### Operating System

- [x] macOS
- [x] Linux
- [x] Windows
- [ ] Other (Please specify)

**Comment by Cammisuli** [comment]
Thanks for your report. I'm actively looking at what could be causing the issue.

**Comment by valentinpalkovic** [comment]
We have the exact same issue in Storybook's mono repository:
https://github.com/storybookjs/storybook/actions/runs/12338536418/job/34433600345

Unfortunately, we were not able to reproduce it locally. Maybe it has something to do with the GitHub Action actually performing on a Windows OS.

**Comment by robertIsaac** [comment]
@valentinpalkovic 
I have GitHub action on Linux and locally windows and it's working locally but failing on linux

**Comment by Dayonel** [comment]
We are facing the same issue. Works locally but fails during Azure DevOps CI/CD.

**Comment by SonnyRR** [comment]
We've encountered the same issue, but for local runs on Windows machines. This happened more frequently after the upgrade to `v20.3.1`. We haven't removed the `useLegacyCache` flag, but we've set it to `false`. In NX Cloud it seems to execute reliably, but running the tasks locally on a workstation results in the same error & stack trace as mentioned in this issue.

**Comment by faileon** [comment]
> We've encountered the same issue, but for local runs on Windows machines. This happened more frequently after the upgrade to `v20.3.1`. We haven't removed the `useLegacyCache` flag, but we've set it to `false`. In NX Cloud it seems to execute reliably, but running the tasks locally on a workstation results in the same error & stack trace as mentioned in this issue.

I think this was solved with https://github.com/nrwl/nx/issues/28930#issuecomment-2583290499

In my case, I also had to replace the autogenerated:
```json
 "tasksRunnerOptions": {
    "default": {
      "runner": "nx-cloud",
      "options": {
        "nxCloudId": "<YOUR_ID>"
      }
    }
  }
```
with just:
```json
    "nxCloudId": "<YOUR_ID>"
```

and then uninstalling nx-cloud from my local packages:
```
pnpm rm nx-cloud
```

**Comment by robertIsaac** [comment]
@faileon I get different error now
> 401: Unable to connect to Nx Cloud

**Comment by faileon** [comment]
> [@faileon](https://github.com/faileon) I get different error now
> 
> > 401: Unable to connect to Nx Cloud

401 is unauthorized, try `nx-cloud login`

**Comment by robertIsaac** [comment]
I found I need to modify my github workflow file and to add the new token in the repo secrets doing
so now this is fixed
but the code issue is back 😂

**Comment by robertIsaac** [comment]
> > [@faileon](https://github.com/faileon) I get different error now
> > > 401: Unable to connect to Nx Cloud
> 
> 401 is unauthorized, try `nx-cloud login`

this only works locally not in the ci

**Comment by faileon** [comment]
> > > [@faileon](https://github.com/faileon) I get different error now
> > > > 401: Unable to connect to Nx Cloud
> > 
> > 
> > 401 is unauthorized, try `nx-cloud login`
> 
> this only works locally not in the ci

In CI you can use the CI access token https://nx.dev/ci/recipes/security/access-tokens

**Comment by robertIsaac** [comment]
@faileon I used it and now it passes if `useLegacyCache` is true, and fail if false
exactly same as before

**Comment by Cammisuli** [comment]
I've been trying hard to reproduce this, and haven't had much success. @robertIsaac is your CI runs available for me to look at? Or have some kind of reproducible case that I can poke around with?

**Comment by robertIsaac** [comment]
hi @Cammisuli 

https://cloud.nx.app/runs/wYqtqVo3Wx

I can give you access to the repo too if needed

**Comment by Cammisuli** [comment]
Thanks @robertIsaac, I don't see the `code` issue in that particular run on Nx Cloud. If its on the CI side on your repo, then if you don't mind giving me access so that I can look more into it, I appreciate it 🙏🏼

**Comment by robertIsaac** [comment]
@Cammisuli can you follow me on Twitter so I can message you there

**Comment by Cammisuli** [comment]
A new version of Nx Cloud is going to be deployed today to fix this issue.
