### ISSUE TITLE
Transitive internal workspace libraries aren’t included in Webpack/Rspack externals allowlist

### ISSUE THREAD

**Issue by warnellw** [nrwl/nx#31217]
### Current Behavior

Both the Nx Webpack and Rspack plugins compute their `allowlist` for `webpack-node-externals` using only the direct entries in `graph.dependencies[projectName]`. Neither implementation recurses into dependencies-of-dependencies, so any transitive libs get treated as externals and are omitted from the bundle. As a result, if A → B → C, only B is bundled and C is treated as external, leading to missing modules at runtime:

Webpack plugin at [apply-base-config.ts#L358](https://github.com/nrwl/nx/blob/cc22a0760113b10a0c6a67249c25f9651693e73f/packages/webpack/src/plugins/nx-webpack-plugin/lib/apply-base-config.ts#L358)

Rspack plugin at [apply-base-config.ts#L356](https://github.com/nrwl/nx/blob/889dee0854df50997cd36b03f109dd3965c147a6/packages/rspack/src/plugins/utils/apply-base-config.ts#L356)

### Expected Behavior

All internal workspace libraries - both direct and transitive - should be discovered via the project graph and added to the externals `allowlist`. As a result, if A → B → C, only B is bundled and C is treated as external under the current logic; fixing this issue, both B and C would be bundled correctly, preventing missing-module errors at runtime.

### Steps to Reproduce

1. Generate a NestJS application A in an Nx workspace (v20.8.1+ or v21.0.3) along with two libraries, B and C
2. Establish transitive imports: have A depend on B, and B depend on C
3. Build the NestJS app A
4. Inspect the built output (e.g.`dist/main.js`)
5. Observe that C is treated as an external dependency (and fails to load at runtime), while B is correctly bundled

### Nx Report

```shell
Node           : 22.13.1
OS             : linux-arm64
Native Target  : aarch64-linux
yarn           : 1.22.22

nx                     : 20.8.1
@nx/js                 : 20.8.1
@nx/jest               : 20.8.1
@nx/eslint             : 20.8.1
@nx/workspace          : 20.8.1
@nx/cypress            : 20.8.1
@nx/devkit             : 20.8.1
@nx/eslint-plugin      : 20.8.1
@nx/module-federation  : 20.8.1
@nx/nest               : 20.8.1
@nx/next               : 20.8.1
@nx/node               : 20.8.1
@nx/plugin             : 20.8.1
@nx/react              : 20.8.1
@nx/vite               : 20.8.1
@nx/web                : 20.8.1
@nx/webpack            : 20.8.1
typescript             : 5.7.3
---------------------------------------
Registered Plugins:
@nx/cypress/plugin
@nx/js/typescript
@nx/webpack/plugin
---------------------------------------
```

### Failure Logs

```shell

```

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by nicolas-marien** [comment]
Hello 👋 
I am facing this issue, and indeed the graph appears to only contain the explicit dependencies of a node.
What I'll patch on my end for now would be something like that. 
Given a function 

```typescript
   function traverseDependencies(
      name: string,
      graph: Record<string, ProjectGraphDependency[]>,
      visited: Set<string>
    ) {
      const output: ProjectGraphDependency[] = [];

      const localDeps = (graph[name] ?? []).filter(
        (dep) => !dep.target.startsWith('npm:')
      );

      for (const dep of localDeps) {
        if (visited.has(dep.target)) {
          continue;
        }
        visited.add(dep.target);
        output.push(dep);
        output.push(...traverseDependencies(dep.target, graph, visited));
      }
      return output;
    }
```

I would build the `deps` array like so:

```typescript
  const visitedDependencies = new Set<string>();
    const deps = traverseDependencies(
      projectName,
      graph.dependencies,
      visitedDependencies
    );
```

@ndcunningham (sorry for the wild ping 🙈), I see that the current code has been introduced w/ https://github.com/nrwl/nx/pull/30538
Would the suggested solution make sense? 
Thanks!

**Comment by Forceres** [comment]
Any official updates?

**Comment by Coly010** [comment]
This issue has been fixed in PR #31343 (commit f1171191dd) which added support for retrieving all transitive non-buildable dependencies in both Webpack and Rspack plugins.

The fix ensures that when building Node.js applications, both direct and transitive workspace library dependencies are properly included in the webpack-node-externals allowlist, preventing the runtime errors described in this issue.

Fix details:
- Enhanced getNonBuildableLibs function to traverse transitive dependencies
- Added getAllTransitiveDeps utility function with circular dependency protection
- Applied to both @nx/webpack and @nx/rspack packages

The fix is available in the latest version of Nx.

**Comment by Forceres** [comment]
What about buildable libs? Does it work for buildable libs?

**Comment by Milananas** [comment]
@Forceres for me it doesn't, the same issue exists with buildable libs still (both with Webpack and Rspack). 
I have currently added this custom webpack plugin as a temporary fix:

```
class CustomNxWebpackAddon {
  apply(compiler) {
    const projectRoot = path.join(__dirname, '../../');

    compiler.hooks.afterEnvironment.tap('CustomNxWebpackAddon', () => {
      compiler.options.externals = nodeExternals({
        modulesDir: `${projectRoot}/node_modules`,
        allowlist: [/^@my-monorepo/] // replace with a shared prefix for your libs (or list every lib separately)
      });

      compiler.options.resolve.symlinks = false;
    });
  }
}
```

**Comment by Forceres** [comment]
> [@Forceres](https://github.com/Forceres) for me it doesn't, the same issue exists with buildable libs still (both with Webpack and Rspack). I have currently added this custom webpack plugin as a temporary fix:
> 
> ```
> class CustomNxWebpackAddon {
>   apply(compiler) {
>     const projectRoot = path.join(__dirname, '../../');
> 
>     compiler.hooks.afterEnvironment.tap('CustomNxWebpackAddon', () => {
>       compiler.options.externals = nodeExternals({
>         modulesDir: `${projectRoot}/node_modules`,
>         allowlist: [/^@my-monorepo/] // replace with a shared prefix for your libs (or list every lib separately)
>       });
> 
>       compiler.options.resolve.symlinks = false;
>     });
>   }
> }
> ```

Thanks for custom code, try to integrate it in my scenario.

**Comment by Milananas** [comment]
@Coly010 , any ideas why buildable libs still don't work? Anything we're doing wrong?
