### ISSUE TITLE
Shared Vitest Setup Re-initializes Angular TestBed

### ISSUE THREAD

**Issue by thanh-nguyen-codeleap** [nrwl/nx#33434]
### Current Behavior

Vitest setup file tet.ts, referenced by every project via vite.shared-config.ts, calls TestBed.initTestEnvironment unconditionally. When Nx executes multiple test cases in a single Node process , the setup file crash because initTestEnvironment throws Cannot set base providers because it has already been called.

Environment
Nx 22.0.2, Vitest 4.0.7
Angular 20.3.10
Shared setup located at tet.ts, included through vite.shared-config.ts → test.setupFiles

### Expected Behavior

All projects should reuse the existing TestBed or reset it cleanly, allowing multiple Vitest runs per process.

### Steps to Reproduce

1. Run any projects in a command: npx nx test <app-name>
3. Each second test case’s Vitest run fails during bootstrap with: Error: Cannot set base providers because it has already been called.

### Nx Report

```shell
Node           : 22.13.1
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 11.4.2

nx                     : 22.0.2
@nx/js                 : 22.0.2
@nx/eslint             : 22.0.2
@nx/workspace          : 22.0.2
@nx/angular            : 22.0.2
@nx/cypress            : 22.0.2
@nx/devkit             : 22.0.2
@nx/eslint-plugin      : 22.0.2
@nx/module-federation  : 22.0.2
@nx/rspack             : 22.0.2
@nx/storybook          : 22.0.2
@nx/vite               : 22.0.2
@nx/web                : 22.0.2
@nx/webpack            : 22.0.2
typescript             : 5.9.3
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
---------------------------------------
Community plugins:
@analogjs/vite-plugin-angular : 2.0.3
@analogjs/vitest-angular      : 2.0.3
@jsverse/transloco            : 8.1.0
@ngrx/component-store         : 20.1.0
@ngxpert/hot-toast            : 5.1.2
@storybook/angular            : 8.6.14
angular-eslint                : 20.5.1
---------------------------------------
Cache Usage: 4.15 MB / 46.04 GB
```

### Failure Logs

```shell
Error: Cannot set base providers because it has already been called
   ❯ _TestBedImpl.initTestEnvironment ../../../darwin_arm64-fastbuild-ST-199a4f3c4e20/bin/packages/core/testing/src/test_bed.ts:477:13
   ❯ ../../tet.ts:108:9
      106| 
      107| const testBed = getTestBed();
      108| testBed.initTestEnvironment(BrowserTestingModule, platformBrowserTesti…


```

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

**Comment by rujorgensen** [comment]
I'm facing the same issue, but only when running in CI (Github Actions). I'm curious as to why it's different there than running locally, but I haven't had the time to look into it in depth yet.

**Comment by thanh-nguyen-codeleap** [comment]
> I'm facing the same issue, but only when running in CI (Github Actions). I'm curious as to why it's different there than running locally, but I haven't had the time to look into it in depth yet.

Yes, I only encounter the issue on CI Github Action but it works fine locally. And one more thing is if I only have one app running vitest while others run jest in my monorepo, then there's no issue on the pipeline

**Comment by rujorgensen** [comment]
I've got no idea why I suddenly see this issue, but I found the solution [here](https://cookbook.marmicode.io/angular/testing/migrating-to-vitest#-common-errors--issues). I made the changes below and now it works in my CI 🤷‍♂️.

(shamelessly stolen from https://cookbook.marmicode.io/angular/testing/migrating-to-vitest#-common-errors--issues)

Replace:

```TypeScript 
getTestBed().initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting(),
);
```
with:

```TypeScript
beforeEach(() => {
  getTestBed().initTestEnvironment(
    BrowserDynamicTestingModule,
    platformBrowserDynamicTesting(),
  );
});

afterEach(() => {
  getTestBed().resetTestEnvironment();
});
```

**Comment by axelforsti** [comment]
seems to be an issue in vitest: https://github.com/vitest-dev/vitest/issues/8944

**Comment by Coly010** [comment]
This should be solved on the latest version of Nx

**Comment by skoropadas** [comment]
@Coly010 I'm experiencing the same issue after updating to 22.3.1 and vitest 4, but it works if I downgrade vitest to v3

**Comment by thanh-nguyen-codeleap** [comment]
> @Coly010 I'm experiencing the same issue after updating to 22.3.1 and vitest 4, but it works if I downgrade vitest to v3

Stay at vitest 4.04 or the lower version will help.

**Comment by skoropadas** [comment]
> Stay at vitest 4.04 or the lower version will help.

yep, that works for me, thanks!

**Comment by DaSchTour** [comment]
I still have this issue with 22.3.1 and Vitest 4.0.8 and AnalogJS 2.2.0
After setting the version to 4.0.4 it works.
So it feels like the issue is not solved 100%
Or maybe there is also some changes to the configuration needed that are not highlighted the way I would have spotted it.
