### ISSUE TITLE
ng add @nrwl/schematics throws - Error: ENOENT: no such file or directory, stat 'src/favicon.ico'

### ISSUE THREAD

**Issue by matthewharwood** [nrwl/nx#543]
Recreation:
```
ng new universalproject
cd universalproject
ng g universal --client-project universalproject // optional
ng add @nrwl/schematics
ng serve --project=universalproject
```

Throws this error:
```
Error: ENOENT: no such file or directory, stat '/Users/matty/dev/morningharwood/src/favicon.ico'
    at Object.fs.statSync (fs.js:946:3)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (/Users/matty/dev/morningharwood/node_modules/@angular/cli/node_modules/@angular-devkit/core/node/host.js:222:25)
    at Observable.subscribe (/Users/matty/dev/morningharwood/node_modules/rxjs/internal/Observable.js:162:69)
    at MapOperator.call (/Users/matty/dev/morningharwood/node_modules/rxjs/internal/operators/map.js:62:23)
    at Observable.subscribe (/Users/matty/dev/morningharwood/node_modules/rxjs/internal/Observable.js:159:22)
    at CatchOperator.call (/Users/matty/dev/morningharwood/node_modules/rxjs/internal/operators/catchError.js:28:23)
    at Observable.subscribe (/Users/matty/dev/morningharwood/node_modules/rxjs/internal/Observable.js:159:22)
    at MapOperator.call (/Users/matty/dev/morningharwood/node_modules/rxjs/internal/operators/map.js:62:23)
    at Observable.subscribe (/Users/matty/dev/morningharwood/node_modules/rxjs/internal/Observable.js:159:22)
    at /Users/matty/dev/morningharwood/node_modules/rxjs/internal/util/subscribeTo.js:22:31
    at Object.subscribeToResult (/Users/matty/dev/morningharwood/node_modules/rxjs/internal/util/subscribeToResult.js:7:45)
    at new ForkJoinSubscriber (/Users/matty/dev/morningharwood/node_modules/rxjs/internal/observable/forkJoin.js:165:57)
    at Observable._subscribe (/Users/matty/dev/morningharwood/node_modules/rxjs/internal/observable/forkJoin.js:145:16)
    at Observable.subscribe (/Users/matty/dev/morningharwood/node_modules/rxjs/internal/Observable.js:162:69)
    at /Users/matty/dev/morningharwood/node_modules/rxjs/internal/util/subscribeTo.js:22:31
    at Object.subscribeToResult (/Users/matty/dev/morningharwood/node_modules/rxjs/internal/util/subscribeToResult.js:7:45)
```

If I try to change the paths to match in the `angular.json` 
```
"options": {
            "outputPath": "dist/apps/universalproject",
            "index": "apps/universalproject/src/index.html",
            "main": "apps/universalproject/src/main.ts",
            "polyfills": "apps/universalproject/src/polyfills.ts",
            "tsConfig": "apps/universalproject/src/tsconfig.app.json",
            "assets": [
              "apps/universalproject/src/favicon.ico",
              "apps/universalproject/src/assets"
            ],
            "styles": [
              "apps/universalproject/src/styles.css"
            ],
            "scripts": []
          },
```

I get an error:
`ng serve --project=universalproject
```
The apps/universalproject/src/favicon.ico asset path must start with the project source root.
Error: The apps/universalproject/src/favicon.ico asset path must start with the project source root.
    at assetPatterns.map.assetPattern (/Users/matty/dev/universalproject/node_modules/@angular-devkit/build-angular/src/utils/normalize-asset-patterns.js:37:23)
    at Array.map (<anonymous>)
    at Object.normalizeAssetPatterns (/Users/matty/dev/universalproject/node_modules/@angular-devkit/build-angular/src/utils/normalize-asset-patterns.js:30:10)
    at MergeMapSubscriber.check_port_1.checkPort.pipe.operators_1.concatMap [as project] (/Users/matty/dev/universalproject/node_modules/@angular-devkit/build-angular/src/dev-server/index.js:34:372)
    at MergeMapSubscriber._tryNext (/Users/matty/dev/universalproject/node_modules/rxjs/internal/operators/mergeMap.js:122:27)
    at MergeMapSubscriber._next (/Users/matty/dev/universalproject/node_modules/rxjs/internal/operators/mergeMap.js:112:18)
    at MergeMapSubscriber.Subscriber.next (/Users/matty/dev/universalproject/node_modules/rxjs/internal/Subscriber.js:103:18)
    at MergeMapSubscriber.notifyNext (/Users/matty/dev/universalproject/node_modules/rxjs/internal/operators/mergeMap.js:141:26)
    at InnerSubscriber._next (/Users/matty/dev/universalproject/node_modules/rxjs/internal/InnerSubscriber.js:30:21)
    at InnerSubscriber.Subscriber.next (/Users/matty/dev/universalproject/node_modules/rxjs/internal/Subscriber.js:103:18)
    at /Users/matty/dev/universalproject/node_modules/rxjs/internal/util/subscribeTo.js:17:28
    at Object.subscribeToResult (/Users/matty/dev/universalproject/node_modules/rxjs/internal/util/subscribeToResult.js:7:45)
    at MergeMapSubscriber._innerSub (/Users/matty/dev/universalproject/node_modules/rxjs/internal/operators/mergeMap.js:132:38)
    at MergeMapSubscriber._tryNext (/Users/matty/dev/universalproject/node_modules/rxjs/internal/operators/mergeMap.js:129:14)
    at MergeMapSubscriber._next (/Users/matty/dev/universalproject/node_modules/rxjs/internal/operators/mergeMap.js:112:18)
    at MergeMapSubscriber.Subscriber.next (/Users/matty/dev/universalproject/node_modules/rxjs/internal/Subscriber.js:103:18)
```

**Comment by FrozenPandaz** [comment]
Was there an error when doing `ng add @nrwl/schematics`?

**Comment by FrozenPandaz** [comment]
Ah yeah, you're affected by this issue which has been fixed, but not published 
```sh
EISDIR: illegal operation on a directory, read
```

https://github.com/nrwl/nx/issues/513

**Comment by shabbirdesap** [comment]
I am facing the same issue but it's not resolved for me.

**Comment by matthewharwood** [comment]
@FrozenPandaz Retry'd with latest. 

> The `EISDIR: illegal operation on a directory, read` #513
Has been resolved but now when running `ng serve --project=universalproject`
I get an ngrx error:

```
ERROR in node_modules/@ngrx/effects/src/actions.d.ts(2,10): error TS2305: Module '"/Users/matty/dev/universalproject/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/@ngrx/effects/src/actions.d.ts(3,10): error TS2305: Module '"/Users/matty/dev/universalproject/node_modules/rxjs/Operator"' has no exported member 'Operator'.
node_modules/@ngrx/effects/src/effect_notification.d.ts(1,10): error TS2305: Module '"/Users/matty/dev/universalproject/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/@ngrx/effects/src/effect_notification.d.ts(2,10): error TS2305: Module '"/Users/matty/dev/universalproject/node_modules/rxjs/Notification"' has no exported member 'Notification'.
node_modules/@ngrx/effects/src/effect_sources.d.ts(1,10): error TS2305: Module '"/Users/matty/dev/universalproject/node_modules/rxjs/Subject"' has no exported member 'Subject'.
node_modules/@ngrx/effects/src/effects_resolver.d.ts(1,10): error TS2305: Module '"/Users/matty/dev/universalproject/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/@ngrx/effects/src/on_run_effects.d.ts(1,10): error TS2305: Module '"/Users/matty/dev/universalproject/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/@ngrx/store/src/actions_subject.d.ts(2,10): error TS2305: Module '"/Users/matty/dev/universalproject/node_modules/rxjs/BehaviorSubject"' has no exported member 'BehaviorSubject'.
node_modules/@ngrx/store/src/reducer_manager.d.ts(2,10): error TS2305: Module '"/Users/matty/dev/universalproject/node_modules/rxjs/BehaviorSubject"' has no exported member 'BehaviorSubject'.
node_modules/@ngrx/store/src/reducer_manager.d.ts(3,10): error TS2305: Module '"/Users/matty/dev/universalproject/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/@ngrx/store/src/scanned_actions_subject.d.ts(2,10): error TS2305: Module '"/Users/matty/dev/universalproject/node_modules/rxjs/Subject"' has no exported member 'Subject'.
node_modules/@ngrx/store/src/state.d.ts(2,10): error TS2305: Module '"/Users/matty/dev/universalproject/node_modules/rxjs/BehaviorSubject"' has no exported member 'BehaviorSubject'.
node_modules/@ngrx/store/src/state.d.ts(3,10): error TS2305: Module '"/Users/matty/dev/universalproject/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/@ngrx/store/src/store.d.ts(2,10): error TS2305: Module '"/Users/matty/dev/universalproject/node_modules/rxjs/Observer"' has no exported member 'Observer'.
node_modules/@ngrx/store/src/store.d.ts(3,10): error TS2305: Module '"/Users/matty/dev/universalproject/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/@ngrx/store/src/store.d.ts(4,10): error TS2305: Module '"/Users/matty/dev/universalproject/node_modules/rxjs/Operator"' has no exported member 'Operator'.
node_modules/rxjs/BehaviorSubject.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/BehaviorSubject'.
node_modules/rxjs/Notification.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Notification'.
node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
node_modules/rxjs/Observer.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observer'.
node_modules/rxjs/Operator.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Operator'.
node_modules/rxjs/Subject.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Subject'.

ℹ ｢wdm｣: Failed to compile.
```

**Comment by matthewharwood** [comment]
It would seem that this:
https://github.com/nrwl/nx/issues/164
now points to the next universal bug:


> This functionality broke recently. After extending @ngrx/schematics.This should be fixed in @ngrx/schematics@6.0.0? But we can add a fix to extend it.
> -- FrozenPandaz

**Comment by FrozenPandaz** [comment]
Yes there is a fix for that in this [PR](https://github.com/nrwl/nx/pull/558). Sorry about that. To resolve the `rxjs-compat` issues you can install `rxjs-compat` in your workspace.

#164 Is still an issue, I fixed adding Nx to a Angular CLI Universal project, but.. not Universal to a Nx project lol. Do not fear, I will get to it :)

I'm going to close this issue for now as the original issue is resolved. For the `rxjs-compat` issue, you could create an issue and I will refer to it in my PR.
