### ISSUE TITLE
Adding custom files are not picked up by compiler

### ISSUE THREAD

**Issue by rogerfar** [nrwl/nx#5825]
I have a React project with multiple libraries. One of those libraries has a component with missing typings.

According to the TypeScripts docs I have to add those files to the `files` section in `tsconfig.json`. 

I updated my `tsconfig.json` for the library to include them:

```
{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "jsx": "react-jsx",
    "allowJs": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true
  },
  "files": ["./src/types/react-height.d.ts"],
  "include": [],
  "references": [
    {
      "path": "./tsconfig.lib.json"
    },
    {
      "path": "./tsconfig.spec.json"
    }
  ]
}
```

Contents of `react-height.d.ts`:
```
declare module 'react-height' {
  export class ReactHeight extends React.Component<ReactHeightProps> {}

  interface ReactHeightProps {
    onHeightReady: (height: number) => void;
  }
}
```

When I now use the component as normal:

```
import ReactGridLayout, { Layout } from 'react-grid-layout';

export const GridLayout: React.FC<> = (props) => {
  return (
    <ReactHeight onHeightReady={(value: number) => recalculateHeight(value, component)}>
		<ComponentLoader config={component}></ComponentLoader>
	  </ReactHeight>
  );
};
```
VsCode now references this file as I can ctrl+click on the component and it jumps to the d.ts file.

But when compiling:
```
TS7016: Could not find a declaration file for module 'react-height'. 'C:/Projects/test/client/node_modules/react-height/lib/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react-height` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-height';`
```

It doesn't seem to pickup the d.ts files. Are those d.ts files supposed to be defined somewhere else?

**Comment by FrozenPandaz** [comment]
Hm I can see how that is confusing.

> Are those d.ts files supposed to be defined somewhere else.

You can see that the array was empty before because the `tsconfig.json` files in projects are what is known as a [Solution Style Tsconfig](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#support-for-solution-style-tsconfigjson-files)

As a result, you want to add those `.d.ts` files to the `tsconfig.lib.json` and the `tsconfig.spec.json` files array. This should solve the issue.

That should solve your issue. Please re-open this issue if it does not.

**Comment by rogerfar** [comment]
@FrozenPandaz I tried adding to the `tsconfig.lib.json` file:
```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist/out-tsc",
    "types": ["node", "webpack-env"]
  },
  "files": [
    "../../node_modules/@nrwl/react/typings/cssmodule.d.ts",
    "../../node_modules/@nrwl/react/typings/image.d.ts",
    "src/@types/react-table/react-table-config.d.ts"
  ],
  "exclude": ["**/*.spec.ts", "**/*.spec.tsx"],
  "include": ["**/*.js", "**/*.jsx", "**/*.ts", "**/*.tsx"]
}
```
(different d.ts now), but same issue, TS isn't picking up the definition file, which is odd because nrwl adds their own, which seem to work OK.

**Comment by Tatamethues** [comment]
@rogerfar Hi, How did you fix this?

**Comment by rogerfar** [comment]
Added the file to `/libs/libname/src/@types/react-table/react-table-config.d.ts`

Added it to the `tsconfig.lib.json` for the `libname` project:

```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist/out-tsc",
    "types": ["node", "webpack-env"]
  },
  "files": [
    "../../node_modules/@nrwl/react/typings/cssmodule.d.ts",
    "../../node_modules/@nrwl/react/typings/image.d.ts",
    "src/@types/react-table/react-table-config.d.ts"
  ],
  "exclude": ["**/*.spec.ts", "**/*.spec.tsx"],
  "include": ["**/*.js", "**/*.jsx", "**/*.ts", "**/*.tsx"]
}
```

But then, I also references it from the files that needed it, that's the important part:

So my React component called `Table.tsx` has this line on top:
`/// <reference path="../../../@types/react-table/react-table-config.d.ts" />`

**Comment by Vadi** [comment]
Not sure if this approach works. I tried exactly as per your steps @rogerfar still getting the error when running nx.

**Comment by Schavras** [comment]
I had a similar issue with the definitions for react table. The way i resolved it was to add a 
```
// noinspection ES6UnusedImports
import * as ReactTableDefinitions from '../reactTableDefinitions';
``` 
 in my top level index.ts file, to point to the reactTableDefinitions.d.ts file,  similary to rogerfar's answer, but without the change in the tsconfig files. 

After this change, i was able to pass the type check and build my next.js app.

**Comment by jonybekov** [comment]
> 

This solution worked for me. But I need an explanation why it works

**Comment by maciejregula** [comment]
Well, it seems that while compiling the app, typescript compiler doesn't see reactTableDefinitions.d.ts file which is in your lib.
When you import reactTableDefinitions.d.ts inside your index.ts of your lib and you use the lib in your app it will work.
For example when you do:
```js
import {SomeComponent} from "@yourNamespace/shared/youLib";
```
The app loads index.ts which has the import type definitions of react-table.
