### ISSUE TITLE
eslint executor performance improvement

### ISSUE THREAD

**Issue by rraziel** [nrwl/nx#9377]
- [x] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description

The ability to specify which tsconfig files to use when using eslint.

## Motivation

Currently, linting a small (few lines), 0 dependency project within a large monorepo can be very slow.

Looking at the behavior, it seems that eslint is going through a lot of files unrelated to the project itself, likely from using the root tsconfig.

Being able to use the project's tsconfig files (e.g. tsconfig.lib.json and tsconfig.spec.json) greatly reduces the linting time:

```sh
# 27 seconds with Nx
nx lint projectname --no-cache 
# 1 second with eslint
eslint --parser-options project:./packages/projectname/tsconfig.*.json ./packages/projectname/src/**/*.ts
```

## Suggested Implementation

Add a new property to the `@nrwl/linter:eslint` executor schema, either:

- `tsConfig` (to match `@nrwl/node:package`) or
- `project` (to match eslint's argument)

```json
{
  "executor": "@nrwl/linter:eslint",
  "options": {
    "lintFilePatterns": ["packages/projectname/src/**/*.ts"],
    "tsConfig": "./packages/projectname/tsconfig.*.json"
  }
}
```

The string value would be passed as `--parser-options project:<string-value-here>`.

```sh
eslint --parser-options project:./packages/projectname/tsconfig.*.json ./packages/projectname/src/**/*.ts
```

A migration would update any existing targets that use the executor to include the new parameter for all projects.

## Alternate Implementations

A more global `parserOptions` property that acts as a dictionary could also work, being more flexible but likely less user-friendly:

```json
{
  "executor": "@nrwl/linter:eslint",
  "options": {
    "lintFilePatterns": ["packages/projectname/src/**/*.ts"],
    "parserOptions": {
      "project": "./packages/projectname/tsconfig.*.json"
    }
  }
}
```

Command-line:

```sh
eslint --parser-options project:./packages/projectname/tsconfig.*.json ./packages/projectname/src/**/*.ts
```

**Comment by meeroslav** [comment]
Hi @rraziel, I ran some tests today on this branch: https://github.com/meeroslav/test-nx-eslint-core-speed. The solution has been created with the latest version of nx.

Here are the results for:
Node v14
![Screenshot 2022-05-05 at 15 16 05](https://user-images.githubusercontent.com/881612/166930908-cb0d7dc3-c003-4cf3-abe5-70d89c1c39de.png)

Node v16
![Screenshot 2022-05-05 at 15 21 54](https://user-images.githubusercontent.com/881612/166932002-ea318eb9-e946-4fa5-a7bc-bc7718ccdb30.png)

Node v18
![Screenshot 2022-05-05 at 15 24 23](https://user-images.githubusercontent.com/881612/166932473-c219debe-4f22-4e74-bdbc-3feb332af171.png)

While pure eslint is a bit faster for v16 and v18 the speed difference is not critical.

Can you tell me which environment you were using by running `nx report`?

**Comment by rraziel** [comment]
Hello @meeroslav,

I don't think the environment (as in versions) matters much, but rather the number of libraries: I have ~500 libs (as in Nx projects) in the workspace.

So:

- in your test with 1 lib and 1 app, worst case it'll go through both to lint just the lib
- in my workspace it'll go through 500 libs to lint just 1 lib 😅

Note: but just in case, it's Nx 13.2.2 on Node 16

**Comment by meeroslav** [comment]
Ok, I see what you mean. I just tried on a repo with ~60 projects and `nx lint` run  went to 4s, while `eslint` remained around 1s. I will look into this more deeper

**Comment by meeroslav** [comment]
Hey @rraziel,

Could you please try to run the test again with the v14.5.4 and using the default task runner (`nx-cloud` runner has some slight performance impact which we will look into this week). Your `nx.json` should look something like this:

```jsonc
{
  // some config before ...
  "tasksRunnerOptions": {
    "default": {
      "runner": "nx/tasks-runners/default",
      "options": {
        "cacheableOperations": ["build", "lint", "test", "e2e"]
      }
    }
  },
  // more config after ...
}
```

Based on recent improvements done on linter and task runners, running linter on monorepos with 60-80 projects gives similar results for both nx and direct eslint. To make runs comparable run:

```bash
npx nx run my-project:lint --skip-nx-cache
✨  Done in 1.82s.

Bigger project in 75 project repo:
Range (min … max):   12.413 s … 14.915 s
```
and 
```bash
npx eslint "path-to-my-project/**/*.ts" --format=stylish
✨  Done in 1.53s.

Bigger project in 75 project repo:
Range (min … max):   12.126 s … 14.743 s
```

Using `project` actually slows it down for me
```bash
npx eslint "path-to-my-project/**/*.ts" --format=stylish  --parser-options project:"path-to-my-project/tsconfig.*.json"
✨  Done in 2.25s.

Bigger project in 75 project repo:
Range (min … max):   21.163 s … 27.254 s
```

**Comment by meeroslav** [comment]
The current performance cost for using `@nrwl/nx-cloud` task runner can be somewhere between 500ms and 2s but it's a fixed cost and depends mostly on the distance to nx-cloud services and storage.

The remaining run time (also when using default task runner) is almost equal to using plan `eslint` (a few 100ms are spent on nx code, and local caching but nothing significant).

Therefore, I think the issue is resolved.

If you can still reproduce it with the latest version (v14.5.4) please provide a reproduction repository.

**Comment by rraziel** [comment]
Hello,

Sorry I hadn't noticed you closed the issue.

I'm actually on 14.5.4 with a completely unrelated repository right now and the issue is still very much present: linting a literally empty project (just an `index.ts` with `export {};`) takes 8 seconds with nx lint while taking 2 seconds with plain eslint, with still the very same problem of linting every file in the entire monorepo:

Nx

```
Measure-Command { pnpm nx run testproj:lint --skip-nx-cache }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 8
Milliseconds      : 247
Ticks             : 82470491
TotalDays         : 9.54519571759259E-05
TotalHours        : 0.00229084697222222
TotalMinutes      : 0.137450818333333
TotalSeconds      : 8.2470491
TotalMilliseconds : 8247.0491
```

eslint

```
Measure-Command { pnpm eslint "packages/testproj/src/**/*.ts" --parser-options project:"packages/testproj/tsconfig.lib.json" }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 2
Milliseconds      : 225
Ticks             : 22257372
TotalDays         : 2.57608472222222E-05
TotalHours        : 0.000618260333333333
TotalMinutes      : 0.03709562
TotalSeconds      : 2.2257372
TotalMilliseconds : 2225.7372
```

eslint with the entire monorepo

```
 Measure-Command { pnpm eslint "packages/testproj/src/**/*.ts" --parser-options project:"tsconfig.base.json" }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 7
Milliseconds      : 648
Ticks             : 76484525
TotalDays         : 8.8523755787037E-05
TotalHours        : 0.00212457013888889
TotalMinutes      : 0.127474208333333
TotalSeconds      : 7.6484525
TotalMilliseconds : 7648.4525
```

The nx.json task runner is the default:

```json
{
  "tasksRunnerOptions": {
    "default": {
      "runner": "nx/tasks-runners/default",
      "options": {
        "cacheableOperations": ["build", "lint", "test", "e2e"]
      }
    }
  }
}
```

The lint target from the empty project:

```json
{
    "lint": {
      "executor": "@nrwl/linter:eslint",
      "outputs": ["{options.outputFile}"],
      "options": {
        "lintFilePatterns": ["packages/testproj/src/**/*.ts"]
      }
    }
}
```

The .eslintrc.json is also some generated default:

```json
{
  "extends": ["../../.eslintrc.json"],
  "ignorePatterns": ["!**/*"],
  "overrides": [
    {
      "files": ["*.ts", "*.tsx", "*.js", "*.jsx"],
      "rules": {}
    },
    {
      "files": ["*.ts", "*.tsx"],
      "rules": {}
    },
    {
      "files": ["*.js", "*.jsx"],
      "rules": {}
    }
  ]
}
```

Linting any of the ~180 projects in this monorepo takes the exact same amount of time (since it lints all files).

**Comment by rraziel** [comment]
And the Nx report:

```
   Node : 18.1.0
   OS   : win32 x64
   pnpm : 7.9.0

   nx : 14.5.4
   @nrwl/angular : 14.5.4
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : Not Found
   @nrwl/eslint-plugin-nx : 14.5.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.4
   @nrwl/js : 14.5.4
   @nrwl/linter : 14.5.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.5.4
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/workspace : 14.5.4
   typescript : 4.7.4
```

**Comment by rraziel** [comment]
Also, from taking a quick look at #11226 I'm not sure how it would provided any improvement with the bug described here (again, the first message I wrote when opening the issue had a fix in there...)

**Comment by rraziel** [comment]
Any chance I can get some reply/feedback on this?
This is costing quite a bit of money due to the extra time spent on the CI... (and I assume it makes Nx Cloud builds slower too anyway)

**Comment by meeroslav** [comment]
Hey @rraziel, sorry to keep you waiting.

Any chance you can provide a repro repository where I could see these differences?
The tests that I was trying on always returned the same results or even worse when tsconfig was specified.

In the meantime let me reopen the issue.

**Comment by meeroslav** [comment]
These are the results from running the commands in nx repo:

```bash
time yarn eslint "packages/linter/**/*.ts" --parser-options project:"packages/linter/tsconfig.*.json" --format=tap
```

```
1..48
ok 1 - /Users/miro/Dev/nrwl/nx/packages/linter/index.ts
ok 2 - /Users/miro/Dev/nrwl/nx/packages/linter/jest.config.ts
ok 3 - /Users/miro/Dev/nrwl/nx/packages/linter/migrations.spec.ts
ok 4 - /Users/miro/Dev/nrwl/nx/packages/linter/src/executors/eslint/compat.ts
ok 5 - /Users/miro/Dev/nrwl/nx/packages/linter/src/executors/eslint/hasher.ts
ok 6 - /Users/miro/Dev/nrwl/nx/packages/linter/src/executors/eslint/lint.impl.spec.ts
ok 7 - /Users/miro/Dev/nrwl/nx/packages/linter/src/executors/eslint/lint.impl.ts
ok 8 - /Users/miro/Dev/nrwl/nx/packages/linter/src/executors/eslint/schema.d.ts
ok 9 - /Users/miro/Dev/nrwl/nx/packages/linter/src/executors/eslint/utility/eslint-utils.spec.ts
ok 10 - /Users/miro/Dev/nrwl/nx/packages/linter/src/executors/eslint/utility/eslint-utils.ts
ok 11 - /Users/miro/Dev/nrwl/nx/packages/linter/src/generators/init/init.spec.ts
ok 12 - /Users/miro/Dev/nrwl/nx/packages/linter/src/generators/init/init.ts
ok 13 - /Users/miro/Dev/nrwl/nx/packages/linter/src/generators/lint-project/lint-project.spec.ts
ok 14 - /Users/miro/Dev/nrwl/nx/packages/linter/src/generators/lint-project/lint-project.ts
ok 15 - /Users/miro/Dev/nrwl/nx/packages/linter/src/generators/utils/eslint-file.spec.ts
ok 16 - /Users/miro/Dev/nrwl/nx/packages/linter/src/generators/utils/eslint-file.ts
ok 17 - /Users/miro/Dev/nrwl/nx/packages/linter/src/generators/utils/linter.ts
ok 18 - /Users/miro/Dev/nrwl/nx/packages/linter/src/generators/workspace-rule/workspace-rule.spec.ts
ok 19 - /Users/miro/Dev/nrwl/nx/packages/linter/src/generators/workspace-rule/workspace-rule.ts
ok 20 - /Users/miro/Dev/nrwl/nx/packages/linter/src/generators/workspace-rules-project/workspace-rules-project.spec.ts
ok 21 - /Users/miro/Dev/nrwl/nx/packages/linter/src/generators/workspace-rules-project/workspace-rules-project.ts
ok 22 - /Users/miro/Dev/nrwl/nx/packages/linter/src/migrations/update-12-4-0/remove-eslint-project-config-if-no-type-checking-rules.spec.ts
ok 23 - /Users/miro/Dev/nrwl/nx/packages/linter/src/migrations/update-12-4-0/remove-eslint-project-config-if-no-type-checking-rules.ts
ok 24 - /Users/miro/Dev/nrwl/nx/packages/linter/src/migrations/update-12-9-0/add-outputs.spec.ts
ok 25 - /Users/miro/Dev/nrwl/nx/packages/linter/src/migrations/update-12-9-0/add-outputs.ts
ok 26 - /Users/miro/Dev/nrwl/nx/packages/linter/src/migrations/update-13-3-0/eslint-8-updates.spec.ts
ok 27 - /Users/miro/Dev/nrwl/nx/packages/linter/src/migrations/update-13-3-0/eslint-8-updates.ts
ok 28 - /Users/miro/Dev/nrwl/nx/packages/linter/src/migrations/update-14-1-9/add-swc-deps-if-needed.ts
ok 29 - /Users/miro/Dev/nrwl/nx/packages/linter/src/migrations/update-14-4-4/experimental-to-utils-deps.spec.ts
ok 30 - /Users/miro/Dev/nrwl/nx/packages/linter/src/migrations/update-14-4-4/experimental-to-utils-deps.ts
ok 31 - /Users/miro/Dev/nrwl/nx/packages/linter/src/migrations/update-14-4-4/experimental-to-utils-rules.spec.ts
ok 32 - /Users/miro/Dev/nrwl/nx/packages/linter/src/migrations/update-14-4-4/experimental-to-utils-rules.ts
ok 33 - /Users/miro/Dev/nrwl/nx/packages/linter/src/migrations/update-15-0-0/add-eslint-inputs.spec.ts
ok 34 - /Users/miro/Dev/nrwl/nx/packages/linter/src/migrations/update-15-0-0/add-eslint-inputs.ts
ok 35 - /Users/miro/Dev/nrwl/nx/packages/linter/src/utils/convert-tslint-to-eslint/convert-nx-enforce-module-boundaries-rule.spec.ts
ok 36 - /Users/miro/Dev/nrwl/nx/packages/linter/src/utils/convert-tslint-to-eslint/convert-nx-enforce-module-boundaries-rule.ts
ok 37 - /Users/miro/Dev/nrwl/nx/packages/linter/src/utils/convert-tslint-to-eslint/convert-to-eslint-config.spec.ts
ok 38 - /Users/miro/Dev/nrwl/nx/packages/linter/src/utils/convert-tslint-to-eslint/convert-to-eslint-config.ts
ok 39 - /Users/miro/Dev/nrwl/nx/packages/linter/src/utils/convert-tslint-to-eslint/example-tslint-configs.ts
ok 40 - /Users/miro/Dev/nrwl/nx/packages/linter/src/utils/convert-tslint-to-eslint/index.ts
ok 41 - /Users/miro/Dev/nrwl/nx/packages/linter/src/utils/convert-tslint-to-eslint/project-converter.spec.ts
ok 42 - /Users/miro/Dev/nrwl/nx/packages/linter/src/utils/convert-tslint-to-eslint/project-converter.ts
ok 43 - /Users/miro/Dev/nrwl/nx/packages/linter/src/utils/convert-tslint-to-eslint/utils.spec.ts
ok 44 - /Users/miro/Dev/nrwl/nx/packages/linter/src/utils/convert-tslint-to-eslint/utils.ts
ok 45 - /Users/miro/Dev/nrwl/nx/packages/linter/src/utils/rules-requiring-type-checking.ts
ok 46 - /Users/miro/Dev/nrwl/nx/packages/linter/src/utils/testing.ts
ok 47 - /Users/miro/Dev/nrwl/nx/packages/linter/src/utils/versions.ts
ok 48 - /Users/miro/Dev/nrwl/nx/packages/linter/src/utils/workspace-lint-rules.ts

✨  Done in 4.03s.
yarn eslint "packages/linter/**/*.ts" --parser-options  --format=tap  5.46s user 0.69s system 143% cpu 4.290 total
```

```bash
time yarn nx run linter:lint --skip-nx-cache --format=tap
```

```
1..48
ok 1 - /Users/miro/Dev/nrwl/nx/packages/linter/index.ts
ok 2 - /Users/miro/Dev/nrwl/nx/packages/linter/jest.config.ts
ok 3 - /Users/miro/Dev/nrwl/nx/packages/linter/migrations.spec.ts
ok 4 - /Users/miro/Dev/nrwl/nx/packages/linter/src/executors/eslint/compat.ts
ok 5 - /Users/miro/Dev/nrwl/nx/packages/linter/src/executors/eslint/hasher.ts
ok 6 - /Users/miro/Dev/nrwl/nx/packages/linter/src/executors/eslint/lint.impl.spec.ts
ok 7 - /Users/miro/Dev/nrwl/nx/packages/linter/src/executors/eslint/lint.impl.ts
ok 8 - /Users/miro/Dev/nrwl/nx/packages/linter/src/executors/eslint/schema.d.ts
ok 9 - /Users/miro/Dev/nrwl/nx/packages/linter/src/executors/eslint/utility/eslint-utils.spec.ts
ok 10 - /Users/miro/Dev/nrwl/nx/packages/linter/src/executors/eslint/utility/eslint-utils.ts
ok 11 - /Users/miro/Dev/nrwl/nx/packages/linter/src/generators/init/init.spec.ts
ok 12 - /Users/miro/Dev/nrwl/nx/packages/linter/src/generators/init/init.ts
ok 13 - /Users/miro/Dev/nrwl/nx/packages/linter/src/generators/lint-project/lint-project.spec.ts
ok 14 - /Users/miro/Dev/nrwl/nx/packages/linter/src/generators/lint-project/lint-project.ts
ok 15 - /Users/miro/Dev/nrwl/nx/packages/linter/src/generators/utils/eslint-file.spec.ts
ok 16 - /Users/miro/Dev/nrwl/nx/packages/linter/src/generators/utils/eslint-file.ts
ok 17 - /Users/miro/Dev/nrwl/nx/packages/linter/src/generators/utils/linter.ts
ok 18 - /Users/miro/Dev/nrwl/nx/packages/linter/src/generators/workspace-rule/workspace-rule.spec.ts
ok 19 - /Users/miro/Dev/nrwl/nx/packages/linter/src/generators/workspace-rule/workspace-rule.ts
ok 20 - /Users/miro/Dev/nrwl/nx/packages/linter/src/generators/workspace-rules-project/workspace-rules-project.spec.ts
ok 21 - /Users/miro/Dev/nrwl/nx/packages/linter/src/generators/workspace-rules-project/workspace-rules-project.ts
ok 22 - /Users/miro/Dev/nrwl/nx/packages/linter/src/migrations/update-12-4-0/remove-eslint-project-config-if-no-type-checking-rules.spec.ts
ok 23 - /Users/miro/Dev/nrwl/nx/packages/linter/src/migrations/update-12-4-0/remove-eslint-project-config-if-no-type-checking-rules.ts
ok 24 - /Users/miro/Dev/nrwl/nx/packages/linter/src/migrations/update-12-9-0/add-outputs.spec.ts
ok 25 - /Users/miro/Dev/nrwl/nx/packages/linter/src/migrations/update-12-9-0/add-outputs.ts
ok 26 - /Users/miro/Dev/nrwl/nx/packages/linter/src/migrations/update-13-3-0/eslint-8-updates.spec.ts
ok 27 - /Users/miro/Dev/nrwl/nx/packages/linter/src/migrations/update-13-3-0/eslint-8-updates.ts
ok 28 - /Users/miro/Dev/nrwl/nx/packages/linter/src/migrations/update-14-1-9/add-swc-deps-if-needed.ts
ok 29 - /Users/miro/Dev/nrwl/nx/packages/linter/src/migrations/update-14-4-4/experimental-to-utils-deps.spec.ts
ok 30 - /Users/miro/Dev/nrwl/nx/packages/linter/src/migrations/update-14-4-4/experimental-to-utils-deps.ts
ok 31 - /Users/miro/Dev/nrwl/nx/packages/linter/src/migrations/update-14-4-4/experimental-to-utils-rules.spec.ts
ok 32 - /Users/miro/Dev/nrwl/nx/packages/linter/src/migrations/update-14-4-4/experimental-to-utils-rules.ts
ok 33 - /Users/miro/Dev/nrwl/nx/packages/linter/src/migrations/update-15-0-0/add-eslint-inputs.spec.ts
ok 34 - /Users/miro/Dev/nrwl/nx/packages/linter/src/migrations/update-15-0-0/add-eslint-inputs.ts
ok 35 - /Users/miro/Dev/nrwl/nx/packages/linter/src/utils/convert-tslint-to-eslint/convert-nx-enforce-module-boundaries-rule.spec.ts
ok 36 - /Users/miro/Dev/nrwl/nx/packages/linter/src/utils/convert-tslint-to-eslint/convert-nx-enforce-module-boundaries-rule.ts
ok 37 - /Users/miro/Dev/nrwl/nx/packages/linter/src/utils/convert-tslint-to-eslint/convert-to-eslint-config.spec.ts
ok 38 - /Users/miro/Dev/nrwl/nx/packages/linter/src/utils/convert-tslint-to-eslint/convert-to-eslint-config.ts
ok 39 - /Users/miro/Dev/nrwl/nx/packages/linter/src/utils/convert-tslint-to-eslint/example-tslint-configs.ts
ok 40 - /Users/miro/Dev/nrwl/nx/packages/linter/src/utils/convert-tslint-to-eslint/index.ts
ok 41 - /Users/miro/Dev/nrwl/nx/packages/linter/src/utils/convert-tslint-to-eslint/project-converter.spec.ts
ok 42 - /Users/miro/Dev/nrwl/nx/packages/linter/src/utils/convert-tslint-to-eslint/project-converter.ts
ok 43 - /Users/miro/Dev/nrwl/nx/packages/linter/src/utils/convert-tslint-to-eslint/utils.spec.ts
ok 44 - /Users/miro/Dev/nrwl/nx/packages/linter/src/utils/convert-tslint-to-eslint/utils.ts
ok 45 - /Users/miro/Dev/nrwl/nx/packages/linter/src/utils/rules-requiring-type-checking.ts
ok 46 - /Users/miro/Dev/nrwl/nx/packages/linter/src/utils/testing.ts
ok 47 - /Users/miro/Dev/nrwl/nx/packages/linter/src/utils/versions.ts
ok 48 - /Users/miro/Dev/nrwl/nx/packages/linter/src/utils/workspace-lint-rules.ts

✨  Done in 2.57s.
yarn nx run linter:lint --skip-nx-cache --format=tap  1.96s user 0.26s system 78% cpu 2.841 total
```

As you can see, both runs went through the exact same files and did not touch any additional projects. And running `eslint` with `project` specified takes min 1s (or 33%) longer on this repo.

Please note that I changed `lintFilePatterns` in `project.json` to also match `packages/linter/**/*.ts`.

**Comment by rraziel** [comment]
Thanks for the reply and for reopening the issue.

I can't really provide the repository as it is (because none of them are opensource 🥲) but I will try the commands to see if they yield some additional info. 

And then worst case I can try to create a "dumb" reproduction where most ts files are the same (shouldn't matter for this test).

**Comment by rraziel** [comment]
So,  I did the same thing you did above, with --format=tap, and it looks like once it starts actually linting it's as fast in both cases, but there is a larger delay with Nx before it starts displaying the "ok N" lines (note: there are 23 .ts files in there):

eslint with the parser option (1.8 seconds)

```
Measure-Command { pnpm eslint "packages/testproj/**/*.ts" --parser-options project:"packages/testproj/tsconfg.*.json" --format=tap }


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 1
Milliseconds      : 781
Ticks             : 17815242
TotalDays         : 2.06194930555556E-05
TotalHours        : 0.000494867833333333
TotalMinutes      : 0.02969207
TotalSeconds      : 1.7815242
TotalMilliseconds : 1781.5242
```

eslint without the parser option (7.9 seconds)

```
Measure-Command { pnpm eslint "packages/testproj/**/*.ts" --format=tap }


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 7
Milliseconds      : 920
Ticks             : 79204784
TotalDays         : 9.16722037037037E-05
TotalHours        : 0.00220013288888889
TotalMinutes      : 0.132007973333333
TotalSeconds      : 7.9204784
TotalMilliseconds : 7920.4784
```

Nx (8.4 seconds)

```
Measure-Command { pnpm nx run testproj:lint --skip-nx-cache --format=tap }


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 8
Milliseconds      : 419
Ticks             : 84196470
TotalDays         : 9.74496180555556E-05
TotalHours        : 0.00233879083333333
TotalMinutes      : 0.14032745
TotalSeconds      : 8.419647
TotalMilliseconds : 8419.647
```

**Comment by rraziel** [comment]
Alright, so...

I also retrieved the Nx repository + ran your commands, got pretty much the same results you did.

So I started comparing all the potentially relevant config files (project.json, eslintrc.json, etc.).

Turns out the root `.eslintrc.json` (in both monorepos) has this:

```json
{
  "overrides": [
    {
      "parserOptions": {
        "project": "./tsconfig.*?.json"
      }
    }
  ]
}
```

Removing that `parserOptions` drops the duration quite a bit:

```
Measure-Command { pnpm nx run testproj:lint --skip-nx-cache --format=tap }


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 2
Milliseconds      : 328
Ticks             : 23285727
TotalDays         : 2.69510729166667E-05
TotalHours        : 0.00064682575
TotalMinutes      : 0.038809545
TotalSeconds      : 2.3285727
TotalMilliseconds : 2328.5727
```

From the git history, it seems like it was set by Nx at some point a very long time ago, so I assume [some migration](https://github.com/nrwl/nx/pull/5798) was supposed to remove it but somehow didn't for these 2 monorepos, maybe because they used type-based rules?

So in practice, that `parserOptions` I offered to add when opening the ticket had actually been added months ago because that very same problem had been noticed already... would have been nice starting with that information back in March 🥲

**Comment by meeroslav** [comment]
So, with that override removed, you still get `2.3s` for `nx` and `1.7s` for clean `eslint`?
Do you mind using [hyperfine](https://github.com/sharkdp/hyperfine) for e.g. 20 runs with 1 run warm-up and tell me the results for all three commands on your repo (with override removed of course)?

Please note that running `nx` will always have a small overhead of calculating task hash (and depending on the state of the repo also recalculating graph) but that should be a one-time fixed cost.

**Comment by rraziel** [comment]
I can run additional tests if you think it's useful, but from my point of view dropping the override solved the issue.

I expect Nx to always be slightly slower because it does a bit more, wrapping eslint itself, but it's not - imo - a significant overhead (here it's 0.5s but as you mentioned there's warm-up/etc.) and it will be largely compensated by running affected:lint or the Nx cache anyway.

So up to you, you can close this issue or I can grab some extra metrics 🤔

**Comment by meeroslav** [comment]
In practice, our background daemon should remove most of the Nx overhead so as you said two runs should be very comparable.

Thank you for the clarification and sorry it took us so long to get to the bottom of this.
I will close this issue. If we stumble upon this again we can open a new one.
