### ISSUE TITLE
Cannot read property 'includes' of undefined storybook-configuration

### ISSUE THREAD

**Issue by guyindepurker** [nrwl/nx#9702]
## Current Behavior

`adding .storybook folder to the root directory - 
     based on the Storybook version installed (v6), we'll bootstrap a scaffold for that particular version.
adding .storybook folder to app - using Storybook version 6
Cannot read property 'includes' of undefined`
![Screen Shot 2022-04-06 at 11 26 36](https://user-images.githubusercontent.com/55409919/161931131-c7f170f8-2a88-4aed-97c6-e9085f759a03.png)

## Expected Behavior

I want that the storybook successfully created
## Steps to Reproduce

I am already upgrade the nx env to 13.9.7 from 13.8.5
And it not fix the problem.

### Failure Logs

`adding .storybook folder to the root directory - 
     based on the Storybook version installed (v6), we'll bootstrap a scaffold for that particular version.
adding .storybook folder to app - using Storybook version 6
Cannot read property 'includes' of undefined`
### Environment

Node : 14.19.0
   OS   : darwin x64
   npm  : 6.14.16
   
   nx : 13.9.7
   @nrwl/angular : Not Found
   @nrwl/cypress : 13.9.7
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.9.7
   @nrwl/eslint-plugin-nx : 13.9.7
   @nrwl/express : 13.9.7
   @nrwl/jest : 13.9.7
   @nrwl/js : 13.9.7
   @nrwl/linter : 13.9.7
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 13.9.7
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 13.9.7
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.9.7
   @nrwl/web : 13.9.7
   @nrwl/workspace : 13.9.7
   typescript : 4.5.5
   rxjs : 6.6.7

**Comment by mandarini** [comment]
Hey I thought we fixed that!!!! I'll look into it again

**Comment by mandarini** [comment]
Yea, I thought [that](https://github.com/nrwl/nx/pull/9561/files) would have fixed it, but no. So [I chained all `includes`](https://github.com/nrwl/nx/pull/9707) to make sure.

**Comment by guyindepurker** [comment]
> Yea, I thought [that](https://github.com/nrwl/nx/pull/9561/files) would have fixed it, but no. So [I chained all `includes`](https://github.com/nrwl/nx/pull/9707) to make sure.

Ok so what i need to do right now?

**Comment by mandarini** [comment]
@guyindepurker  Oh, right. First the PR needs to be merged. Then, you would have to update to the version of Nx that will contain this code (most probably 13.10).

**Comment by JosepSalvat** [comment]
@mandarini Still happening. I've tried to create the storybook and says the same.
After using: `nx g @nrwl/react:storybook-configuration project-name` ofc I changed the project-name :D 

Upgraded from 13.4 to 13.10.1 and still happening

**Comment by mandarini** [comment]
@JosepSalvat can you send me a reproduction repo, plz? And plz can you run `nx report` and send me the result?
