### ISSUE TITLE
Nx 13.10 breaks `jest-runner-groups`

### ISSUE THREAD

**Issue by Ezard** [nrwl/nx#9873]
## Preface
For those unaware, `jest-runner-groups` allows you to "annotate" a test file with a group name, e.g.
```
/**
 * @group foo
 */
```
This allows you to only run certain tests

## Current Behavior
When using `jest-runner-groups`:
- `nx affected:test --group=foo` runs tests that have not been annotated with the group `foo`
- `nx affected:test --group=-foo` runs tests that have been annotated with the group `foo`
- If I manually run Jest in one of the apps/libs, then the `--group` flag works as expected

## Expected Behavior
When using `jest-runner-groups`:
- `nx affected:test --group=foo` should only run tests that have been annotated with the group `foo`
- `nx affected:test --group=-foo` should only run tests that have not been annotated with the group `foo`

## Steps to Reproduce
1. Use `jest-runner-groups` in a repo using Nx `13.9.7`, and see that test filtering works as expected
2. Update Nx to 13.10.2, and see that all tests are run, regardless of what `--group` flag is passed

### Failure Logs
n/a

### Environment
```
Node : 16.14.1
OS   : win32 x64
npm  : 8.5.0

nx : 13.10.2
@nrwl/angular : Not Found
@nrwl/cypress : Not Found
@nrwl/detox : Not Found
@nrwl/devkit : 13.10.2
@nrwl/eslint-plugin-nx : 13.10.2
@nrwl/express : Not Found
@nrwl/jest : 13.10.2
@nrwl/js : 13.10.2
@nrwl/linter : 13.10.2
@nrwl/nest : 13.10.2
@nrwl/next : Not Found
@nrwl/node : 13.10.2
@nrwl/nx-cloud : 13.3.1
@nrwl/nx-plugin : Not Found
@nrwl/react : Not Found
@nrwl/react-native : Not Found
@nrwl/schematics : Not Found
@nrwl/storybook : Not Found
@nrwl/web : Not Found
@nrwl/workspace : 13.10.2
typescript : 4.3.5
rxjs : 7.5.5
```

At a guess, I'd say that the `--group` flag isn't actually being passed to Jest, even though Nx says that it is running the command with that flag

**Comment by barbados-clemens** [comment]
I just realized that jest-runner-groups is a 3rd party jest plugin that enables this extra functionality. so adding it to the schema is probably not the way forward. I'll look into different options in allowing "extra args" to be passed into jest. 
right now we manually assign the properties expected by jest.

**Comment by Ezard** [comment]
@barbados-clemens thanks for looking into this

Unfortunately, I just tried updating Nx (to 14.0.2) and this issue still occurs

e.g. running `npx nx run my-app:test --group=integration` results in some tests incorrectly being run, whereas running `npx jest --group=integration` in the `apps/my-app` directory results in those tests not being run (which is correct)

**Comment by Ezard** [comment]
@barbados-clemens so I think I've figured out why it still doesn't work

Before Nx 13.10, the the value of `process.argv` received by `jest-runner-groups` was something like this:
```
[
  'C:\\Program Files\\nodejs\\node.exe',
  'E:\\path\\to\\workspace\\node_modules\\nx\\src\\cli\\run-cli.js',
  'run',
  'admin-api:test',
  '--group=integration'
]
```
This meant that`jest-runner-groups` could pick up the `--group` arg

However, `process.argv` now looks something like this:
```
[
  'C:\\Program Files\\nodejs\\node.exe',
  'E:\\path\\to\\workspace\\node_modules\\nx\\bin\\run-executor.js',
  '{"targetDescription":{"project":"admin-api","target":"test"},"overrides":{"group":"integration"},"isVerbose":false}'
]
```

I've resolved this for the moment by creating a custom runner with the following code:
```
const GroupRunner = require('jest-runner-groups');

class NxGroupRunner extends GroupRunner {
  runTests(tests, watcher, onStart, onResult, onFailure, options) {
    const config = JSON.parse(process.argv[2]);
    if (config?.overrides?.group) {
      process.argv.push(`--group=${config.overrides.group}`);
    }
    return super.runTests(tests, watcher, onStart, onResult, onFailure, options);
  }
}

module.exports = NxGroupRunner;
```

Whilst this does work, I'm unsure if this should be the correct way going forwards, or if some changes should be made to Nx (obviously this only works for `jest-runner-groups` - there are probably other custom runners that also use args for configuration, but I don't know how commonly they're used)

**Comment by npwork** [comment]
Issue is still present
@Ezard your fix is working, one minor change (if you need to run tests from WebStorm/IntelliJ Idea)

It passes extra arguments, so it's safer to do something like this

```typescript

const GroupRunner = require('jest-runner-groups')

class NxGroupRunner extends GroupRunner {
  runTests(tests, watcher, onStart, onResult, onFailure, options) {
    try {
      const config = JSON.parse(process.argv[2])
      if (config?.overrides?.group) {
        process.argv.push(`--group=${config.overrides.group}`)
      }
    } catch (e) {}
    return super.runTests(tests, watcher, onStart, onResult, onFailure, options)
  }
}

module.exports = NxGroupRunner
```

**Comment by Ezard** [comment]
@npwork thanks for highlighting that :)

I did actually end up modifying my script to check the number of arguments before trying to process them (because like you I ran into issues when testing in WebStorm), but your solution is probably a better catch-all

FYI, I also released this runner as an npm package here: https://www.npmjs.com/package/jest-runner-groups-nx

(I had some issues with using a local JS file, and we also have a bunch of Nx repos, so it made sense to pull it out into a package)

**Comment by Ezard** [comment]
@npwork I've integrated your suggestions into v1.1.0 of `jest-runner-groups-nx` (with a bit of tweaking since, from testing, your solution worked for multiple groups but not single groups)

**Comment by npwork** [comment]
@Ezard  good job!

**Comment by khause** [comment]
This is definitely still an issue we are experiencing. Is there any update on this? as opposed to having to use `jest-runner-groups-nx`.

The `@nrwl/jest` [source code](https://github.com/nrwl/nx/blob/cd4e983e904152be18a97c23e82d8233f8119742/packages/jest/src/executors/jest/jest.impl.ts#L59-L60) states that it should be passing arguments like `--group=<group>` down to `jest cli` as expected.
